import { existsSync, linkSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { json, sha256 } from '../src/files.js';
import { applyProjection, observeProjection, planProjection, PROJECTION_PATHS } from '../src/projection.js';

const MARK = '<!-- Generated by ia host; edit the cited native records. -->';
const made: string[] = [];
const temp = () => {
  const p = mkdtempSync(join(tmpdir(), 'ia-projection-'));
  made.push(p);
  return p;
};
afterEach(() => {
  for (const p of made.splice(0)) rmSync(p, { recursive: true, force: true });
});
const put = (root: string, path: string, text: string) => {
  mkdirSync(dirname(resolve(root, path)), { recursive: true });
  writeFileSync(resolve(root, path), text);
};
const artifacts = (extra = '') => [
  { path: '.claude/rules/ia-workspace.md', text: `${MARK}\n\n# IA workspace${extra}\n` },
  { path: '.claude/skills/ia-authoring/SKILL.md', text: `---\nname: ia-authoring\n---\n\n${MARK}\n` },
  { path: '.claude/agents/demo-steward.md', text: `---\nname: demo-steward\n---\n\n${MARK}\n` },
];
/** A second/third render of the same set: every path's bytes change, so hand-edit tolerance is genuinely exercised. */
const bump = (list: ReturnType<typeof artifacts>, tag: string) =>
  list.map((a) => ({ ...a, text: `${a.text}${tag}\n` }));

it('creates, updates, removes owned stale files and leaves CLAUDE.md alone', () => {
  const root = temp();
  put(root, 'CLAUDE.md', 'mine\n');
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual([]);
  const next = artifacts(' v2').slice(0, 2),
    plan = planProjection({ root, host: 'claude', artifacts: next, marker: MARK });
  expect(plan.actions).toEqual([
    { path: '.claude/agents/demo-steward.md', action: 'remove' },
    { path: '.claude/rules/ia-workspace.md', action: 'update' },
    { path: '.claude/skills/ia-authoring/SKILL.md', action: 'unchanged' },
  ]);
  applyProjection(plan);
  expect(existsSync(resolve(root, '.claude/agents/demo-steward.md'))).toBe(false);
  expect(readFileSync(resolve(root, 'CLAUDE.md'), 'utf8')).toBe('mine\n');
});
it('refuses an unmanaged file, a hand edit and any path outside the allowlist', () => {
  const root = temp();
  put(root, '.claude/rules/ia-workspace.md', 'user file\n');
  expect(() => planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toThrow(
    /unmanaged file at a managed path: \.claude\/rules\/ia-workspace\.md/,
  );
  expect(readFileSync(resolve(root, '.claude/rules/ia-workspace.md'), 'utf8')).toBe('user file\n');
  const other = temp();
  applyProjection(planProjection({ root: other, host: 'claude', artifacts: artifacts(), marker: MARK }));
  put(other, '.claude/rules/ia-workspace.md', `${MARK}\n\nedited\n`);
  expect(observeProjection({ root: other, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual([
    { path: '.claude/rules/ia-workspace.md', drift: 'changed' },
  ]);
  expect(() => planProjection({ root: other, host: 'claude', artifacts: artifacts(), marker: MARK })).toThrow(
    /edited by hand/,
  );
  expect(() =>
    planProjection({ root: temp(), host: 'claude', artifacts: [{ path: 'CLAUDE.md', text: MARK }], marker: MARK }),
  ).toThrow(/outside the claude allowlist/);
  expect(PROJECTION_PATHS.codex).toEqual(['AGENTS.md', '.agents/skills/ia-authoring/SKILL.md']);
});
it('reports outdated and missing files against freshly rendered artifacts', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  rmSync(resolve(root, '.claude/agents/demo-steward.md'));
  expect(observeProjection({ root, host: 'claude', artifacts: artifacts(' v2'), marker: MARK })).toEqual([
    { path: '.claude/agents/demo-steward.md', drift: 'missing' },
    { path: '.claude/rules/ia-workspace.md', drift: 'outdated' },
  ]);
});
it('removes exactly the owned set and leaves CLAUDE.md intact', () => {
  const root = temp();
  put(root, 'CLAUDE.md', 'mine\n');
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  applyProjection(planProjection({ root, host: 'claude', artifacts: [], marker: MARK }));
  for (const artifact of artifacts()) expect(existsSync(resolve(root, artifact.path))).toBe(false);
  expect(existsSync(resolve(root, '.ia/distributions/hosts/claude-projection.json'))).toBe(false);
  expect(readFileSync(resolve(root, 'CLAUDE.md'), 'utf8')).toBe('mine\n');
});
it('refuses a tampered ownership state naming an unallowlisted path or a malformed hash', () => {
  const outside = temp();
  put(
    outside,
    '.ia/distributions/hosts/claude-projection.json',
    json({ format: 'ia.host-projection-state.v1', host: 'claude', files: { 'CLAUDE.md': 'a'.repeat(64) } }),
  );
  expect(() => planProjection({ root: outside, host: 'claude', artifacts: [], marker: MARK })).toThrow(
    /Invalid projection ownership state/,
  );
  expect(() => observeProjection({ root: outside, host: 'claude', artifacts: null, marker: MARK })).toThrow(
    /Invalid projection ownership state/,
  );
  const badHash = temp();
  put(
    badHash,
    '.ia/distributions/hosts/claude-projection.json',
    json({
      format: 'ia.host-projection-state.v1',
      host: 'claude',
      files: { '.claude/rules/ia-workspace.md': 'not-a-sha256' },
    }),
  );
  expect(() => planProjection({ root: badHash, host: 'claude', artifacts: [], marker: MARK })).toThrow(
    /Invalid projection ownership state/,
  );
  const traversal = temp();
  put(
    traversal,
    '.ia/distributions/hosts/claude-projection.json',
    json({ format: 'ia.host-projection-state.v1', host: 'claude', files: { '../outside.md': sha256('x') } }),
  );
  expect(() => planProjection({ root: traversal, host: 'claude', artifacts: [], marker: MARK })).toThrow(
    /Invalid projection ownership state/,
  );
});

// --- Crash safety: an interrupted apply must never look like a hand edit on the next plan/observe. ---
it('keeps an interrupted first apply from looking hand-edited and converges under different artifacts', () => {
  const root = temp(),
    plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  const first = plan.actions[0]!.path; // '.claude/agents/demo-steward.md', alphabetically first, a create
  expect(() =>
    applyProjection(plan, (stage) => {
      if (stage === first) throw new Error('interrupted');
    }),
  ).toThrow('interrupted');
  expect(
    observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }).some(
      (d) => d.drift === 'changed',
    ),
  ).toBe(false);
  const v2 = bump(artifacts(), 'v2');
  applyProjection(planProjection({ root, host: 'claude', artifacts: v2, marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: v2, marker: MARK })).toEqual([]);
});
it('keeps an interrupted update from looking hand-edited and converges under different artifacts', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  const v2 = bump(artifacts(), 'v2'),
    plan = planProjection({ root, host: 'claude', artifacts: v2, marker: MARK });
  const target = plan.actions.find((a) => a.action === 'update')!.path;
  expect(() =>
    applyProjection(plan, (stage) => {
      if (stage === target) throw new Error('interrupted');
    }),
  ).toThrow('interrupted');
  expect(
    observeProjection({ root, host: 'claude', artifacts: v2, marker: MARK }).some((d) => d.drift === 'changed'),
  ).toBe(false);
  const v3 = bump(artifacts(), 'v3');
  applyProjection(planProjection({ root, host: 'claude', artifacts: v3, marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: v3, marker: MARK })).toEqual([]);
});
it('converges after an interrupted removal, leaving CLAUDE.md untouched', () => {
  const root = temp();
  put(root, 'CLAUDE.md', 'mine\n');
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  const plan = planProjection({ root, host: 'claude', artifacts: [], marker: MARK });
  const first = plan.actions[0]!.path;
  expect(() =>
    applyProjection(plan, (stage) => {
      if (stage === first) throw new Error('interrupted');
    }),
  ).toThrow('interrupted');
  applyProjection(planProjection({ root, host: 'claude', artifacts: [], marker: MARK }));
  for (const artifact of artifacts()) expect(existsSync(resolve(root, artifact.path))).toBe(false);
  expect(existsSync(resolve(root, '.ia/distributions/hosts/claude-projection.json'))).toBe(false);
  expect(readFileSync(resolve(root, 'CLAUDE.md'), 'utf8')).toBe('mine\n');
});

// --- Drift kinds beyond changed/missing/outdated. ---
it('distinguishes an unmanaged file from a marked-but-unowned one for a requested path', () => {
  const unowned = temp();
  applyProjection(planProjection({ root: unowned, host: 'claude', artifacts: [artifacts()[1]!], marker: MARK })); // owns only the skill file
  put(unowned, '.claude/rules/ia-workspace.md', 'no marker, never ours\n');
  expect(observeProjection({ root: unowned, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual(
    expect.arrayContaining([{ path: '.claude/rules/ia-workspace.md', drift: 'unmanaged' }]),
  );
  const marked = temp();
  applyProjection(planProjection({ root: marked, host: 'claude', artifacts: [artifacts()[1]!], marker: MARK }));
  put(marked, '.claude/rules/ia-workspace.md', `${MARK}\n\nsomeone else's render\n`);
  expect(observeProjection({ root: marked, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual(
    expect.arrayContaining([{ path: '.claude/rules/ia-workspace.md', drift: 'unowned' }]),
  );
});
it('reports an orphaned marked steward file without deleting or refusing it', () => {
  const root = temp();
  put(root, '.claude/agents/orphan-steward.md', `---\nname: orphan-steward\n---\n\n${MARK}\n`);
  const plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  expect(plan.actions).toEqual(
    expect.arrayContaining([{ path: '.claude/agents/orphan-steward.md', action: 'unowned' }]),
  );
  applyProjection(plan);
  expect(readFileSync(resolve(root, '.claude/agents/orphan-steward.md'), 'utf8')).toBe(
    `---\nname: orphan-steward\n---\n\n${MARK}\n`,
  );
  expect(observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual(
    expect.arrayContaining([{ path: '.claude/agents/orphan-steward.md', drift: 'unowned' }]),
  );
});

// --- Minor validations. ---
it('refuses an artifact whose own text is missing the marker line', () => {
  expect(() =>
    planProjection({
      root: temp(),
      host: 'claude',
      artifacts: [{ path: '.claude/rules/ia-workspace.md', text: '# no marker\n' }],
      marker: MARK,
    }),
  ).toThrow(/missing the marker line/);
});
it('refuses an invalid host with a typed error rather than a TypeError', () => {
  let error: unknown;
  try {
    planProjection({ root: temp(), host: 'gemini' as unknown as 'claude', artifacts: [], marker: MARK });
  } catch (caught) {
    error = caught;
  }
  expect((error as { code?: string }).code).toBe('IA-DIST-INPUT-INVALID');
});
it('refuses a duplicate artifact path', () => {
  const first = artifacts()[0]!;
  expect(() => planProjection({ root: temp(), host: 'claude', artifacts: [first, first], marker: MARK })).toThrow(
    /Duplicate projection path/,
  );
});
it('refuses an artifact exceeding 1 MiB', () => {
  const big = { path: '.claude/rules/ia-workspace.md', text: `${MARK}\n${'x'.repeat(1024 * 1024)}\n` };
  expect(() => planProjection({ root: temp(), host: 'claude', artifacts: [big], marker: MARK })).toThrow(
    /exceeds 1048576 bytes/,
  );
});
it('names line-ending drift in the hand-edit refusal', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  const crlf = readFileSync(resolve(root, '.claude/rules/ia-workspace.md'), 'utf8').replace(/\n/g, '\r\n');
  put(root, '.claude/rules/ia-workspace.md', crlf);
  expect(() => planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toThrow(
    /edited by hand \(line endings differ\)/,
  );
});
it('refuses a marked file the state does not own with its own message', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: [artifacts()[1]!], marker: MARK })); // owns the skill file only
  put(root, '.claude/rules/ia-workspace.md', `${MARK}\n\nsomeone else's render\n`);
  expect(() => planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toThrow(
    /not owned by this workspace's projection state: \.claude\/rules\/ia-workspace\.md; remove it, then rerun/,
  );
});

// --- The orphan scan must be best-effort: a user's own files must never make plan/observe throw. ---
it('skips unreadable files in .claude/agents/ during the orphan scan instead of failing', () => {
  const root = temp();
  mkdirSync(resolve(root, '.claude/agents'), { recursive: true });
  writeFileSync(resolve(root, '.claude/agents/my-agent.md'), Buffer.from([0x66, 0x6f, 0x6f, 0xff, 0xfe, 0x0a])); // invalid UTF-8
  writeFileSync(resolve(root, '.claude/agents/big.md'), Buffer.alloc(1024 * 1024 + 1, 'x')); // over the 1 MiB read limit
  expect(() => planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).not.toThrow();
  expect(() => observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).not.toThrow();
});

// --- The pending accepted-hash set must stay bounded even under repeated interruption. ---
it('bounds the pending accepted set across several consecutive interrupted applies', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  let previous = artifacts();
  for (let round = 0; round < 10; round++) {
    const next = bump(previous, `r${round}`);
    const plan = planProjection({ root, host: 'claude', artifacts: next, marker: MARK });
    const target = plan.actions.find((a) => a.action === 'update')!.path;
    expect(() =>
      applyProjection(plan, (stage) => {
        if (stage === target) throw new Error('interrupted');
      }),
    ).toThrow('interrupted');
    expect(() => observeProjection({ root, host: 'claude', artifacts: next, marker: MARK })).not.toThrow();
    previous = next;
  }
  applyProjection(planProjection({ root, host: 'claude', artifacts: previous, marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: previous, marker: MARK })).toEqual([]);
});
it('resumes correctly when replanned with the same inputs after an interruption', () => {
  const root = temp(),
    plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  const first = plan.actions[0]!.path;
  expect(() =>
    applyProjection(plan, (stage) => {
      if (stage === first) throw new Error('interrupted');
    }),
  ).toThrow('interrupted');
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual([]);
});
it('locates each refusal at the file it concerns', () => {
  const where = (run: () => unknown): { code?: string; path?: string } => {
    try {
      run();
    } catch (error) {
      return error as { code?: string; path?: string };
    }
    return {};
  };
  const root = temp();
  put(root, '.claude/rules/ia-workspace.md', 'user\n');
  expect(where(() => planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }))).toMatchObject({
    code: 'IA-DIST-LOCAL-MODIFICATION',
    path: '.claude/rules/ia-workspace.md',
  });
  const owned = temp();
  applyProjection(planProjection({ root: owned, host: 'claude', artifacts: artifacts(), marker: MARK }));
  put(owned, '.ia/distributions/hosts/claude-projection.json', '{"format":"other"}\n');
  expect(
    where(() => planProjection({ root: owned, host: 'claude', artifacts: artifacts(), marker: MARK })),
  ).toMatchObject({ code: 'IA-DIST-INPUT-INVALID', path: '.ia/distributions/hosts/claude-projection.json' });
});
it('locates each observation failure at the file it concerns', () => {
  const where = (run: () => unknown): { code?: string; path?: string } => {
    try {
      run();
    } catch (error) {
      return error as { code?: string; path?: string };
    }
    return {};
  };
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  linkSync(resolve(root, '.claude/rules/ia-workspace.md'), resolve(root, 'alias.md'));
  expect(where(() => observeProjection({ root, host: 'claude', artifacts: null, marker: MARK }))).toMatchObject({
    code: 'IA-DIST-PATH-UNSAFE',
    path: '.claude/rules/ia-workspace.md',
  });
  rmSync(resolve(root, 'alias.md'));
  put(root, '.ia/distributions/hosts/claude-projection.json', 'garbage\n');
  expect(where(() => observeProjection({ root, host: 'claude', artifacts: null, marker: MARK }))).toMatchObject({
    path: '.ia/distributions/hosts/claude-projection.json',
  });
  const unmanaged = temp();
  applyProjection(
    planProjection({ root: unmanaged, host: 'claude', artifacts: artifacts().slice(0, 2), marker: MARK }),
  );
  put(unmanaged, 'other.md', 'x\n');
  mkdirSync(resolve(unmanaged, '.claude/agents'), { recursive: true });
  linkSync(resolve(unmanaged, 'other.md'), resolve(unmanaged, '.claude/agents/demo-steward.md'));
  expect(
    where(() => observeProjection({ root: unmanaged, host: 'claude', artifacts: artifacts(), marker: MARK })),
  ).toMatchObject({ code: 'IA-DIST-PATH-UNSAFE', path: '.claude/agents/demo-steward.md' });
});
