import {
  existsSync,
  linkSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { json, sha256 } from '../src/files.js';
import { applyProjection, observeProjection, planProjection, PROJECTION_PATHS } from '../src/projection.js';

/** The marker the position packet's files carry (runtime PACKET_MARKER), which the CLI passes as the plan's marker. */
const MARK = '<!-- Generated by ia project; edit the cited native records. -->';
/** B9: the two 1.x markers, compliance's WORKSPACE_PROJECTION_MARKER (ia host) and PROJECTION_MARKER (this repository). */
const HOST_MARK = '<!-- Generated by ia host; edit the cited native records. -->',
  REPO_MARK = '<!-- Generated by tools/projections/generate.ts; edit the cited native records. -->';
const STATE = '.ia/distributions/hosts/claude-projection.json',
  STEWARD = '.claude/agents/demo-steward.md';
const made: string[] = [];
const temp = () => {
  const p = mkdtempSync(join(tmpdir(), 'ia-projection-'));
  made.push(p);
  return p;
};
afterEach(() => {
  for (const p of made.splice(0)) rmSync(p, { recursive: true, force: true });
});
const put = (root: string, path: string, text: string) => {
  mkdirSync(dirname(resolve(root, path)), { recursive: true });
  writeFileSync(resolve(root, path), text);
};
const read = (root: string, path: string) => readFileSync(resolve(root, path), 'utf8');
const artifacts = (extra = '') => [
  { path: '.claude/rules/ia-workspace.md', text: `${MARK}\n\n# IA position packet${extra}\n` },
  { path: '.claude/skills/ia-authoring/SKILL.md', text: `---\nname: ia-authoring\n---\n\n${MARK}\n` },
];
/** A second/third render of the same set: every path's bytes change, so hand-edit tolerance is genuinely exercised. */
const bump = (list: ReturnType<typeof artifacts>, tag: string) =>
  list.map((a) => ({ ...a, text: `${a.text}${tag}\n` }));
/** A 1.x claude projection as `ia host` wrote it: the files, and a state listing each with its digest. */
function legacy(root: string, files: Readonly<Record<string, string>>): void {
  for (const [path, text] of Object.entries(files)) put(root, path, text);
  put(
    root,
    STATE,
    json({
      format: 'ia.host-projection-state.v1',
      host: 'claude',
      files: Object.fromEntries(Object.entries(files).map(([path, text]) => [path, sha256(text)])),
    }),
  );
}
const steward = (marker: string) => `---\nname: demo-steward\n---\n\n${marker}\n\nSource revision: x\n`;
const where = (run: () => unknown): { code?: string; path?: string; message?: string } => {
  try {
    run();
  } catch (error) {
    return error as { code?: string; path?: string; message?: string };
  }
  return {};
};

it('creates, updates, removes owned stale files and leaves CLAUDE.md alone', () => {
  const root = temp();
  put(root, 'CLAUDE.md', 'mine\n');
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual([]);
  const next = artifacts(' v2').slice(0, 1),
    plan = planProjection({ root, host: 'claude', artifacts: next, marker: MARK });
  expect(plan.actions).toEqual([
    { path: '.claude/rules/ia-workspace.md', action: 'update' },
    { path: '.claude/skills/ia-authoring/SKILL.md', action: 'remove' },
  ]);
  applyProjection(plan);
  expect(existsSync(resolve(root, '.claude/skills/ia-authoring/SKILL.md'))).toBe(false);
  expect(read(root, 'CLAUDE.md')).toBe('mine\n');
});
it('refuses an unmanaged file, a hand edit and any path outside the allowlist, a steward file included', () => {
  const root = temp();
  put(root, '.claude/rules/ia-workspace.md', 'user file\n');
  expect(() => planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toThrow(
    /unmanaged file at a managed path: \.claude\/rules\/ia-workspace\.md/,
  );
  expect(read(root, '.claude/rules/ia-workspace.md')).toBe('user file\n');
  const other = temp();
  applyProjection(planProjection({ root: other, host: 'claude', artifacts: artifacts(), marker: MARK }));
  put(other, '.claude/rules/ia-workspace.md', `${MARK}\n\nedited\n`);
  expect(observeProjection({ root: other, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual([
    { path: '.claude/rules/ia-workspace.md', drift: 'changed' },
  ]);
  expect(() => planProjection({ root: other, host: 'claude', artifacts: artifacts(), marker: MARK })).toThrow(
    /edited by hand/,
  );
  // B9: no projection writes a steward file any more, and CLAUDE.md is the repository's, never a consumer's.
  for (const path of ['CLAUDE.md', STEWARD])
    expect(
      where(() => planProjection({ root: temp(), host: 'claude', artifacts: [{ path, text: MARK }], marker: MARK })),
      path,
    ).toMatchObject({ code: 'IA-DIST-PATH-UNSAFE', message: expect.stringContaining('outside the claude allowlist') });
  expect(PROJECTION_PATHS).toEqual({
    claude: ['.claude/rules/ia-workspace.md', '.claude/skills/ia-authoring/SKILL.md'],
    codex: ['AGENTS.md', '.agents/skills/ia-authoring/SKILL.md'],
  });
});
it('reports outdated and missing files against freshly rendered artifacts', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  rmSync(resolve(root, '.claude/skills/ia-authoring/SKILL.md'));
  expect(observeProjection({ root, host: 'claude', artifacts: artifacts(' v2'), marker: MARK })).toEqual([
    { path: '.claude/rules/ia-workspace.md', drift: 'outdated' },
    { path: '.claude/skills/ia-authoring/SKILL.md', drift: 'missing' },
  ]);
});
it('removes exactly the owned set and leaves CLAUDE.md intact', () => {
  const root = temp();
  put(root, 'CLAUDE.md', 'mine\n');
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  applyProjection(planProjection({ root, host: 'claude', artifacts: [], marker: MARK }));
  for (const artifact of artifacts()) expect(existsSync(resolve(root, artifact.path))).toBe(false);
  expect(existsSync(resolve(root, STATE))).toBe(false);
  expect(read(root, 'CLAUDE.md')).toBe('mine\n');
});
it('refuses a tampered ownership state naming an unallowlisted path or a malformed hash', () => {
  const tampered = (files: Record<string, string>, host: 'claude' | 'codex' = 'claude') => {
    const root = temp();
    put(
      root,
      `.ia/distributions/hosts/${host}-projection.json`,
      json({ format: 'ia.host-projection-state.v1', host, files }),
    );
    return root;
  };
  for (const [root, host] of [
    [tampered({ 'CLAUDE.md': 'a'.repeat(64) }), 'claude'],
    [tampered({ '.claude/rules/ia-workspace.md': 'not-a-sha256' }), 'claude'],
    [tampered({ '../outside.md': sha256('x') }), 'claude'],
    // A steward file is a claude path; a codex state never listed one.
    [tampered({ [STEWARD]: sha256('x') }, 'codex'), 'codex'],
    [tampered({ '.claude/agents/Upper.md': sha256('x') }), 'claude'],
  ] as const) {
    expect(() => planProjection({ root, host, artifacts: [], marker: MARK })).toThrow(
      /Invalid projection ownership state/,
    );
    expect(() => observeProjection({ root, host, artifacts: null, marker: MARK })).toThrow(
      /Invalid projection ownership state/,
    );
  }
});

// --- B9: a 1.x projection upgrades in place. ---
it("upgrades a 1.x claude projection: legacy-marked owned files are replaced and the state's steward files deleted", () => {
  const root = temp(),
    rules = `${HOST_MARK}\n\n# IA workspace\n`,
    skill = `---\nname: ia-authoring\n---\n\n${HOST_MARK}\n`;
  legacy(root, {
    '.claude/rules/ia-workspace.md': rules,
    '.claude/skills/ia-authoring/SKILL.md': skill,
    [STEWARD]: steward(HOST_MARK),
    // This repository's own 1.x marker is owned too.
    '.claude/agents/repo-steward.md': steward(REPO_MARK),
  });
  const plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  expect(plan.actions).toEqual([
    { path: STEWARD, action: 'remove' },
    { path: '.claude/agents/repo-steward.md', action: 'remove' },
    { path: '.claude/rules/ia-workspace.md', action: 'update' },
    { path: '.claude/skills/ia-authoring/SKILL.md', action: 'update' },
  ]);
  expect(applyProjection(plan)).toEqual({ status: 'projected', written: 2, removed: 2 });
  expect(existsSync(resolve(root, STEWARD))).toBe(false);
  expect(existsSync(resolve(root, '.claude/agents/repo-steward.md'))).toBe(false);
  for (const artifact of artifacts()) expect(read(root, artifact.path)).toBe(artifact.text);
  // The state format is unchanged; it now lists only what the packet renders.
  expect(JSON.parse(read(root, STATE))).toEqual({
    format: 'ia.host-projection-state.v1',
    host: 'claude',
    files: Object.fromEntries(artifacts().map((artifact) => [artifact.path, sha256(artifact.text)])),
  });
  expect(observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual([]);
  // A codex projection's legacy-marked AGENTS.md is replaced the same way.
  const codex = temp(),
    agents = { path: 'AGENTS.md', text: `${MARK}\n\n# IA position packet\n` };
  put(codex, 'AGENTS.md', `${HOST_MARK}\n\n# IA workspace\n`);
  put(
    codex,
    '.ia/distributions/hosts/codex-projection.json',
    json({
      format: 'ia.host-projection-state.v1',
      host: 'codex',
      files: { 'AGENTS.md': sha256(read(codex, 'AGENTS.md')) },
    }),
  );
  expect(planProjection({ root: codex, host: 'codex', artifacts: [agents], marker: MARK }).actions).toEqual([
    { path: 'AGENTS.md', action: 'update' },
  ]);
});
it('lists every steward file it does not own as foreign and never touches it', () => {
  const root = temp(),
    unmarked = 'my own reviewer\n';
  legacy(root, { [STEWARD]: steward(HOST_MARK), '.claude/agents/listed-mine.md': unmarked });
  // Unlisted: the user's own file, and a marked one another clone or workspace left.
  put(root, '.claude/agents/x.md', unmarked);
  put(root, '.claude/agents/stray-steward.md', steward(HOST_MARK));
  const plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  expect(plan.actions).toEqual([
    { path: STEWARD, action: 'remove' },
    { path: '.claude/agents/listed-mine.md', action: 'foreign' },
    { path: '.claude/agents/stray-steward.md', action: 'foreign' },
    { path: '.claude/agents/x.md', action: 'foreign' },
    { path: '.claude/rules/ia-workspace.md', action: 'create' },
    { path: '.claude/skills/ia-authoring/SKILL.md', action: 'create' },
  ]);
  applyProjection(plan);
  expect(existsSync(resolve(root, STEWARD))).toBe(false);
  expect(read(root, '.claude/agents/listed-mine.md')).toBe(unmarked);
  expect(read(root, '.claude/agents/x.md')).toBe(unmarked);
  expect(read(root, '.claude/agents/stray-steward.md')).toBe(steward(HOST_MARK));
  // The state stops listing the foreign file; the next plan still lists every one, and removal leaves them too.
  expect(Object.keys(JSON.parse(read(root, STATE)).files)).toEqual(artifacts().map((artifact) => artifact.path));
  applyProjection(planProjection({ root, host: 'claude', artifacts: [], marker: MARK }));
  for (const path of ['.claude/agents/listed-mine.md', '.claude/agents/x.md', '.claude/agents/stray-steward.md'])
    expect(existsSync(resolve(root, path)), path).toBe(true);
  // A foreign file is no drift.
  expect(observeProjection({ root, host: 'claude', artifacts: null, marker: MARK })).toEqual([
    { path: '.claude/agents/stray-steward.md', drift: 'unowned' },
  ]);
});
it('refuses a listed steward file edited by hand that keeps its marker, and drops one already gone', () => {
  const root = temp();
  legacy(root, { [STEWARD]: steward(HOST_MARK) });
  put(root, STEWARD, `${steward(HOST_MARK)}edited\n`);
  expect(observeProjection({ root, host: 'claude', artifacts: null, marker: MARK })).toEqual([
    { path: STEWARD, drift: 'changed' },
  ]);
  expect(where(() => planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }))).toMatchObject({
    code: 'IA-DIST-LOCAL-MODIFICATION',
    path: STEWARD,
    message: `Managed file was edited by hand: ${STEWARD}`,
  });
  expect(read(root, STEWARD)).toBe(`${steward(HOST_MARK)}edited\n`);
  // Deleted by the user: no drift, and the apply only drops it from the state.
  rmSync(resolve(root, STEWARD));
  expect(observeProjection({ root, host: 'claude', artifacts: null, marker: MARK })).toEqual([]);
  const plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  expect(plan.actions[0]).toEqual({ path: STEWARD, action: 'remove' });
  applyProjection(plan);
  expect(Object.keys(JSON.parse(read(root, STATE)).files)).not.toContain(STEWARD);
});

// --- Crash safety: an interrupted apply must never look like a hand edit on the next plan/observe. ---
it('keeps an interrupted first apply from looking hand-edited and converges under different artifacts', () => {
  const root = temp(),
    plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  const first = plan.actions[0]!.path; // '.claude/rules/ia-workspace.md', alphabetically first, a create
  expect(() =>
    applyProjection(plan, (stage) => {
      if (stage === first) throw new Error('interrupted');
    }),
  ).toThrow('interrupted');
  expect(
    observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }).some(
      (d) => d.drift === 'changed',
    ),
  ).toBe(false);
  const v2 = bump(artifacts(), 'v2');
  applyProjection(planProjection({ root, host: 'claude', artifacts: v2, marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: v2, marker: MARK })).toEqual([]);
});
it('keeps an interrupted update from looking hand-edited and converges under different artifacts', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  const v2 = bump(artifacts(), 'v2'),
    plan = planProjection({ root, host: 'claude', artifacts: v2, marker: MARK });
  const target = plan.actions.find((a) => a.action === 'update')!.path;
  expect(() =>
    applyProjection(plan, (stage) => {
      if (stage === target) throw new Error('interrupted');
    }),
  ).toThrow('interrupted');
  expect(
    observeProjection({ root, host: 'claude', artifacts: v2, marker: MARK }).some((d) => d.drift === 'changed'),
  ).toBe(false);
  const v3 = bump(artifacts(), 'v3');
  applyProjection(planProjection({ root, host: 'claude', artifacts: v3, marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: v3, marker: MARK })).toEqual([]);
});
it('converges after an interrupted removal, leaving CLAUDE.md untouched', () => {
  const root = temp();
  put(root, 'CLAUDE.md', 'mine\n');
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  const plan = planProjection({ root, host: 'claude', artifacts: [], marker: MARK });
  const first = plan.actions[0]!.path;
  expect(() =>
    applyProjection(plan, (stage) => {
      if (stage === first) throw new Error('interrupted');
    }),
  ).toThrow('interrupted');
  applyProjection(planProjection({ root, host: 'claude', artifacts: [], marker: MARK }));
  for (const artifact of artifacts()) expect(existsSync(resolve(root, artifact.path))).toBe(false);
  expect(existsSync(resolve(root, STATE))).toBe(false);
  expect(read(root, 'CLAUDE.md')).toBe('mine\n');
});
it('converges after an upgrade interrupted between deleting a steward file and writing the packet', () => {
  const root = temp();
  legacy(root, { [STEWARD]: steward(HOST_MARK), '.claude/rules/ia-workspace.md': `${HOST_MARK}\n\n# IA workspace\n` });
  const plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  expect(() =>
    applyProjection(plan, (stage) => {
      if (stage === STEWARD) throw new Error('interrupted');
    }),
  ).toThrow('interrupted');
  expect(existsSync(resolve(root, STEWARD))).toBe(false);
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual([]);
});

// --- Drift kinds beyond changed/missing/outdated. ---
it('distinguishes an unmanaged file from a marked-but-unowned one for a requested path', () => {
  const unowned = temp();
  applyProjection(planProjection({ root: unowned, host: 'claude', artifacts: [artifacts()[1]!], marker: MARK })); // owns only the skill file
  put(unowned, '.claude/rules/ia-workspace.md', 'no marker, never ours\n');
  expect(observeProjection({ root: unowned, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual(
    expect.arrayContaining([{ path: '.claude/rules/ia-workspace.md', drift: 'unmanaged' }]),
  );
  // A legacy marker is owned too: such a file is marked, not unmanaged.
  for (const marker of [MARK, HOST_MARK]) {
    const marked = temp();
    applyProjection(planProjection({ root: marked, host: 'claude', artifacts: [artifacts()[1]!], marker: MARK }));
    put(marked, '.claude/rules/ia-workspace.md', `${marker}\n\nsomeone else's render\n`);
    expect(observeProjection({ root: marked, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual(
      expect.arrayContaining([{ path: '.claude/rules/ia-workspace.md', drift: 'unowned' }]),
    );
  }
});

// --- Minor validations. ---
it('refuses an artifact whose own text is missing the marker line, a legacy marker included', () => {
  for (const text of ['# no marker\n', `${HOST_MARK}\n`])
    expect(() =>
      planProjection({
        root: temp(),
        host: 'claude',
        artifacts: [{ path: '.claude/rules/ia-workspace.md', text }],
        marker: MARK,
      }),
    ).toThrow(/missing the marker line/);
});
it('refuses an invalid host with a typed error rather than a TypeError', () => {
  let error: unknown;
  try {
    planProjection({ root: temp(), host: 'gemini' as unknown as 'claude', artifacts: [], marker: MARK });
  } catch (caught) {
    error = caught;
  }
  expect((error as { code?: string }).code).toBe('IA-DIST-INPUT-INVALID');
});
it('refuses a duplicate artifact path', () => {
  const first = artifacts()[0]!;
  expect(() => planProjection({ root: temp(), host: 'claude', artifacts: [first, first], marker: MARK })).toThrow(
    /Duplicate projection path/,
  );
});
it('refuses an artifact exceeding 1 MiB', () => {
  const big = { path: '.claude/rules/ia-workspace.md', text: `${MARK}\n${'x'.repeat(1024 * 1024)}\n` };
  expect(() => planProjection({ root: temp(), host: 'claude', artifacts: [big], marker: MARK })).toThrow(
    /exceeds 1048576 bytes/,
  );
});
it('names line-ending drift in the hand-edit refusal', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  const crlf = read(root, '.claude/rules/ia-workspace.md').replace(/\n/g, '\r\n');
  put(root, '.claude/rules/ia-workspace.md', crlf);
  expect(() => planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toThrow(
    /edited by hand \(line endings differ\)/,
  );
});
it('refuses a marked file the state does not own with its own message', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: [artifacts()[1]!], marker: MARK })); // owns the skill file only
  put(root, '.claude/rules/ia-workspace.md', `${MARK}\n\nsomeone else's render\n`);
  expect(() => planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toThrow(
    /not owned by this workspace's projection state: \.claude\/rules\/ia-workspace\.md; remove it, then rerun/,
  );
});

// --- The steward-file scan must be best-effort: a user's own files must never make plan/observe throw. ---
it('lists unreadable files in .claude/agents/ as foreign instead of failing', () => {
  const root = temp();
  mkdirSync(resolve(root, '.claude/agents'), { recursive: true });
  writeFileSync(resolve(root, '.claude/agents/my-agent.md'), Buffer.from([0x66, 0x6f, 0x6f, 0xff, 0xfe, 0x0a])); // invalid UTF-8
  writeFileSync(resolve(root, '.claude/agents/big.md'), Buffer.alloc(1024 * 1024 + 1, 'x')); // over the 1 MiB read limit
  const plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  expect(plan.actions.filter((action) => action.action === 'foreign')).toEqual([
    { path: '.claude/agents/big.md', action: 'foreign' },
    { path: '.claude/agents/my-agent.md', action: 'foreign' },
  ]);
  expect(() => observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).not.toThrow();
});

// --- The pending accepted-hash set must stay bounded even under repeated interruption. ---
it('bounds the pending accepted set across several consecutive interrupted applies', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  let previous = artifacts();
  for (let round = 0; round < 10; round++) {
    const next = bump(previous, `r${round}`);
    const plan = planProjection({ root, host: 'claude', artifacts: next, marker: MARK });
    const target = plan.actions.find((a) => a.action === 'update')!.path;
    expect(() =>
      applyProjection(plan, (stage) => {
        if (stage === target) throw new Error('interrupted');
      }),
    ).toThrow('interrupted');
    expect(() => observeProjection({ root, host: 'claude', artifacts: next, marker: MARK })).not.toThrow();
    previous = next;
  }
  applyProjection(planProjection({ root, host: 'claude', artifacts: previous, marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: previous, marker: MARK })).toEqual([]);
});
it('resumes correctly when replanned with the same inputs after an interruption', () => {
  const root = temp(),
    plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  const first = plan.actions[0]!.path;
  expect(() =>
    applyProjection(plan, (stage) => {
      if (stage === first) throw new Error('interrupted');
    }),
  ).toThrow('interrupted');
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  expect(observeProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK })).toEqual([]);
});
it('locates each refusal at the file it concerns', () => {
  const root = temp();
  put(root, '.claude/rules/ia-workspace.md', 'user\n');
  expect(where(() => planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }))).toMatchObject({
    code: 'IA-DIST-LOCAL-MODIFICATION',
    path: '.claude/rules/ia-workspace.md',
  });
  const owned = temp();
  applyProjection(planProjection({ root: owned, host: 'claude', artifacts: artifacts(), marker: MARK }));
  put(owned, STATE, '{"format":"other"}\n');
  expect(
    where(() => planProjection({ root: owned, host: 'claude', artifacts: artifacts(), marker: MARK })),
  ).toMatchObject({ code: 'IA-DIST-INPUT-INVALID', path: STATE });
});
it('locates each observation failure at the file it concerns', () => {
  const root = temp();
  applyProjection(planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }));
  linkSync(resolve(root, '.claude/rules/ia-workspace.md'), resolve(root, 'alias.md'));
  expect(where(() => observeProjection({ root, host: 'claude', artifacts: null, marker: MARK }))).toMatchObject({
    code: 'IA-DIST-PATH-UNSAFE',
    path: '.claude/rules/ia-workspace.md',
  });
  rmSync(resolve(root, 'alias.md'));
  put(root, STATE, 'garbage\n');
  expect(where(() => observeProjection({ root, host: 'claude', artifacts: null, marker: MARK }))).toMatchObject({
    path: STATE,
  });
  // A listed steward file reached through a hard link is refused at that file, by plan and observation alike.
  const linked = temp();
  legacy(linked, { [STEWARD]: steward(HOST_MARK) });
  put(linked, 'other.md', steward(HOST_MARK));
  rmSync(resolve(linked, STEWARD));
  linkSync(resolve(linked, 'other.md'), resolve(linked, STEWARD));
  for (const run of [
    () => observeProjection({ root: linked, host: 'claude', artifacts: artifacts(), marker: MARK }),
    () => planProjection({ root: linked, host: 'claude', artifacts: artifacts(), marker: MARK }),
  ])
    expect(where(run)).toMatchObject({ code: 'IA-DIST-PATH-UNSAFE', path: STEWARD });
  expect(read(linked, STEWARD)).toBe(steward(HOST_MARK));
});

it('never traverses a linked legacy agents directory, with or without recorded legacy ownership', () => {
  const root = temp(),
    outside = temp();
  legacy(root, { [STEWARD]: `${HOST_MARK}\nowned\n` });
  const original = read(root, STEWARD);
  rmSync(resolve(root, '.claude/agents'), { recursive: true });
  put(outside, 'demo-steward.md', original);
  symlinkSync(outside, resolve(root, '.claude/agents'), process.platform === 'win32' ? 'junction' : 'dir');
  const plan = planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK });
  expect(plan.actions).toContainEqual({ path: STEWARD, action: 'foreign' });
  expect(observeProjection({ root, host: 'claude', artifacts: null, marker: MARK })).toEqual([]);
  applyProjection(plan);
  expect(read(outside, 'demo-steward.md')).toBe(original);
  expect(
    planProjection({ root, host: 'claude', artifacts: artifacts(), marker: MARK }).actions.every(
      (a) => a.action === 'unchanged',
    ),
  ).toBe(true);
});
