/**
 * docs/specs/host-plugin-distribution/README.md §6.1 (amended: rendered at apply time). A pure function:
 * the same input always yields the same files, so the caller's digest of the output identifies the plugin.
 */
export const CLAUDE_PLUGIN = 'ia';
export const CLAUDE_MARKETPLACE = 'inventarch';
export const PLUGIN_MARKER = '<!-- Generated by ia host --user; do not edit. -->';
export interface ClaudePluginInput {
  /** plugin.json version: `<cli version>+<first 12 hex of the payload digest>`. */
  readonly version: string;
  readonly cliVersion: string;
  readonly channel: 'checkout' | 'npm' | 'unknown';
  /** Absolute path of the CLI entry that rendered this plugin; the hook runs it first (§8.1, amended). */
  readonly entry: string;
  /** §5's update instruction, which the hook repeats when `ia` cannot be found. */
  readonly install: string;
}
export interface PluginFile {
  readonly path: string;
  readonly text: string;
}
const json = (value: unknown): string => JSON.stringify(value, null, 2) + '\n';
const skill = (name: string, description: string, body: string): string =>
  `---\nname: ${name}\ndescription: ${JSON.stringify(description)}\n---\n\n${PLUGIN_MARKER}\n\n${body}`;

const INIT = skill(
  'init',
  "Offer to initialize an InventArch workspace in this repository, or record the user's answer. Use only when the user's request involves InventArch, .ia records or their governance.",
  [
    "1. Run `ia doctor --json --host claude` and read its `session` field. If this directory is already a workspace, say so and stop. If the session context reports that the user declined initialization here, today or forever, do not offer to initialize: continue with the user's request, and initialize only if the user explicitly asks to in this conversation.",
    '2. Ask the user one question with three choices: initialize now; not today; never for this repository.',
    '3. Initialize now: run `ia init "<repository root>" --host claude` and show the plan, where `<repository root>` is the absolute path of this project, not the shell\'s current directory. Only after the user confirms it, run `ia init "<repository root>" --apply --yes --host claude`.',
    '4. Not today: run `ia init "<repository root>" --decline today --host claude`, then continue with the user\'s request without offering again.',
    '5. Never: run `ia init "<repository root>" --decline forever --host claude`. Do not offer again.',
    '6. Never search the drive, parent directories or other repositories for `.ia` trees or IA tooling. If `ia` is not found, say so and repeat the install instruction from the session context.',
    '',
  ].join('\n'),
);
const DOCTOR = skill(
  'doctor',
  'Report and explain the InventArch state of this environment and workspace.',
  [
    "Run `ia doctor` and explain each row that is not ok. A row's remedy is a command: offer to run it, never run a remedy that changes files without the user's confirmation. `ia doctor` never repairs anything itself.",
    '',
  ].join('\n'),
);
const AUTHORING = skill(
  'authoring',
  'How to author or check .ia records in an initialized workspace: find vocabulary, validate records and inspect an admitted record.',
  [
    "Find a word and its schema in the language catalogue with `ia vocabulary <word> --schema`. Check this workspace's records with `ia validate`. Inspect an admitted record with `ia inspect <identity>`. Validation establishes conformance to the declared schemas, not design quality. When the workspace names a steward for the system you are changing, hand the change to that steward.",
    '',
  ].join('\n'),
);
// Operator decision 2026-09-24: this agent is active in every repository once the plugin is installed, so it is pinned
// to reading and proposing. A subagent cannot start another one, so it names the steward rather than handing off.
const AUTHOR = `---\nname: ia-author\ndescription: ${JSON.stringify("Delegate a multi-step .ia record review or change proposal in an initialized InventArch workspace, grounded only in what ia reports for it. For a change to one system's records, use that system's steward instead.")}\nmodel: inherit\ntools: Read, Glob, Grep, Bash\n---\n\n${PLUGIN_MARKER}\n\nYou review \`.ia\` records and propose changes to them; you do not edit files. Ground every statement in \`ia vocabulary\` (the installed language catalogue), \`ia validate\` and \`ia inspect\` output for this workspace, and cite records by path and line. If the workspace defines a steward for the system being changed, return the proposed change and that steward's name to the caller. If \`ia doctor\` reports no workspace, stop and say so.\n`;
const HOOK = [
  '// Generated by ia host --user; do not edit. docs/specs/host-plugin-distribution/README.md §8.',
  "import { spawn, spawnSync } from 'node:child_process';",
  "import { accessSync, constants, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';",
  "import { homedir } from 'node:os';",
  "import { delimiter, dirname, isAbsolute, join, parse } from 'node:path';",
  "import { fileURLToPath } from 'node:url';",
  'const here = dirname(fileURLToPath(import.meta.url));',
  '// Only fully qualified PATH entries count. An empty or relative entry names the project directory, which the',
  '// repository controls, and on Windows a rooted entry without a drive or share depends on the current drive (LKI-41).',
  'function qualified(path) {',
  "  return isAbsolute(path) && (process.platform !== 'win32' || parse(path).root.length > 1);",
  '}',
  '// PATH entries that count: qualified ones only. Windows allows an entry in quotes and no quote in a file name, so the',
  '// quotes go there; on POSIX a quote is part of a directory name and every entry stays as written.',
  'function pathEntries() {',
  "  const entries = (process.env.PATH || '').split(delimiter);",
  "  return (process.platform === 'win32' ? entries.map((entry) => entry.replace(/\"/g, '')) : entries).filter(qualified);",
  '}',
  '// The hook looks ia up itself on every platform: cmd.exe reports an unknown command only as a localized message',
  '// with exit 1, the status a real ia doctor failure can have, so no shell is ever asked to fail (LKI-40). Only the four',
  '// types cmd.exe starts as programs count; the PATHEXT script types would start through Windows Script Host.',
  'function findOnPath(name) {',
  "  const windows = process.platform === 'win32';",
  "  const names = windows ? ['.com', '.exe', '.bat', '.cmd'].map((extension) => name + extension) : [name];",
  '  for (const dir of pathEntries()) {',
  '    try {',
  '      if (!statSync(dir).isDirectory()) continue;',
  '    } catch { continue; /* a missing directory costs one check, not one per name */ }',
  '    for (const candidate of names) {',
  '      const file = join(dir, candidate);',
  "      if (windows && file.includes('%')) continue; // cmd.exe would expand %NAME% even inside quotes",
  '      try {',
  '        if (!statSync(file).isFile()) continue;',
  '        if (!windows) accessSync(file, constants.X_OK);',
  '        return file;',
  '      } catch { /* absent or not executable: keep looking, as the shell would */ }',
  '    }',
  '  }',
  '  return null;',
  '}',
  '// cmd.exe by absolute path, since a bare cmd.exe would itself be looked up in the current directory first, and never',
  "// ComSpec: Node gives a shell cmd.exe's switches only when its path matches cmd.exe with backslashes, so it would pass",
  '// -c to another program or to cmd.exe spelled with forward slashes. The hook passes the switches itself (LKI-41).',
  'function windowsShell() {',
  "  const root = process.env.SystemRoot || '';",
  "  return join(qualified(root) ? root : 'C:/Windows', 'System32', 'cmd.exe');",
  '}',
  "// cmd.exe's switches, passed verbatim: /d skips AutoRun commands, /v:off stops a delayed expansion that the registry",
  '// turns on from reading a ! in the path, and /s /c runs the line inside the outer quotes as written.',
  'function windowsArgs(file, args) {',
  "  return ['/d', '/v:off', '/s', '/c', '\"\"' + file + '\" ' + args.join(' ') + '\"'];",
  '}',
  '// Every child the hook starts (doctor, an ia launcher, the update refresh) sees only the qualified entries and, on',
  "// Windows, no implicit current directory, so its own lookups (npm's ia.cmd runs node by name; doctor runs git) cannot",
  '// reach the project either (LKI-41).',
  'function childEnv() {',
  '  const env = {};',
  "  for (const [key, value] of Object.entries(process.env)) if (key.toUpperCase() !== 'PATH') env[key] = value;",
  '  const entries = pathEntries();',
  '  // POSIX reads an empty PATH as the current directory, so a PATH with no qualified entry becomes the system one.',
  "  env.PATH = entries.length > 0 || process.platform === 'win32' ? entries.join(delimiter) : '/usr/bin:/bin';",
  "  if (process.platform === 'win32') env.NoDefaultCurrentDirectoryInExePath = '1';",
  '  return env;',
  '}',
  'function main() {',
  '  try {',
  "    const meta = JSON.parse(readFileSync(join(here, '..', 'ia-plugin.json'), 'utf8'));",
  "    const notFound = { context: 'InventArch: the ia CLI was not found. ' + meta.install + ' Do not search the filesystem for IA tooling.', notice: 'IA: the ia CLI was not found; see the session context.' };",
  '    const project = process.env.CLAUDE_PROJECT_DIR || process.cwd();',
  "    const args = ['doctor', '--json', '--host', 'claude'];",
  "    const options = { cwd: project, encoding: 'utf8', timeout: 5000, windowsHide: true };",
  '    const hasEntry = existsSync(meta.entry);',
  "    const found = hasEntry ? null : findOnPath('ia');",
  '    if (!hasEntry && found === null) return notFound;',
  '    // The file found runs by its absolute path, on Windows through cmd.exe (a .cmd launcher needs it), so no step of',
  '    // the launch searches the project directory (LKI-41). Not found is decided here, before anything starts.',
  '    const run = hasEntry',
  '      ? spawnSync(process.execPath, [meta.entry].concat(args), Object.assign({}, options, { env: childEnv() }))',
  "      : process.platform === 'win32'",
  '        ? spawnSync(windowsShell(), windowsArgs(found, args), Object.assign({}, options, { env: childEnv(), windowsVerbatimArguments: true }))',
  '        : spawnSync(found, args, Object.assign({}, options, { env: childEnv() }));',
  "    if (run.error && run.error.code === 'ETIMEDOUT') return { context: 'IA status unavailable: ia doctor timed out.', notice: null };",
  '    if (!run.stdout) {',
  '      const outcome = run.status ?? run.signal;',
  "      if (outcome === null || outcome === undefined) return { context: 'IA status unavailable: ia doctor did not run.', notice: null };",
  "      return { context: 'IA status unavailable: ia doctor exited ' + outcome + '.', notice: null };",
  '    }',
  '    const session = JSON.parse(run.stdout).session;',
  "    if (!session) return { context: 'IA status unavailable: this ia does not report session state. ' + meta.install, notice: null };",
  '    let notice = session.notice;',
  "    if (notice && session.nudge === 'update' && process.env.CLAUDE_PLUGIN_DATA) {",
  '      try {',
  "        const file = join(process.env.CLAUDE_PLUGIN_DATA, 'nudged-on'), today = new Date().toLocaleDateString('en-CA');",
  "        if (existsSync(file) && readFileSync(file, 'utf8') === today) notice = null;",
  '        else { mkdirSync(process.env.CLAUDE_PLUGIN_DATA, { recursive: true }); writeFileSync(file, today); }',
  '      } catch { /* the nudge file is best-effort; never let it block the briefing */ }',
  '    }',
  '    if (Array.isArray(session.refresh) && session.refresh.length > 0) {',
  '      try {',
  "        const child = spawn(session.refresh[0], session.refresh.slice(1), { cwd: homedir(), env: childEnv(), detached: true, stdio: 'ignore', windowsHide: true });",
  "        child.on('error', () => {});",
  '        child.unref();',
  '      } catch { /* the refresh is best-effort; never let it block the briefing */ }',
  '    }',
  "    return { context: session.context.join('\\n'), notice };",
  '  } catch (error) {',
  "    return { context: 'IA status unavailable: ' + (error && error.code ? error.code : 'unexpected error') + '.', notice: null };",
  '  }',
  '}',
  'const result = main();',
  "process.stdout.write(JSON.stringify(Object.assign(result.notice ? { systemMessage: result.notice } : {}, { hookSpecificOutput: { hookEventName: 'SessionStart', additionalContext: result.context } })) + '\\n');",
  'process.exitCode = 0;',
  '',
].join('\n');

export function renderClaudePlugin(input: ClaudePluginInput): readonly PluginFile[] {
  const files: PluginFile[] = [
    {
      path: '.claude-plugin/marketplace.json',
      text: json({
        name: CLAUDE_MARKETPLACE,
        owner: { name: 'InventArch' },
        description:
          'InventArch: session state from ia doctor, and init, doctor and authoring skills for .ia workspaces.',
        plugins: [
          {
            name: CLAUDE_PLUGIN,
            source: './plugins/ia',
            description: 'InventArch front door: session state from ia doctor, and init, doctor and authoring skills.',
          },
        ],
      }),
    },
    {
      path: 'plugins/ia/.claude-plugin/plugin.json',
      text: json({
        name: CLAUDE_PLUGIN,
        version: input.version,
        description:
          'InventArch front door. Reports ia doctor state at session start and offers init, doctor and authoring skills. No engine and no MCP server; workspace registration is ia host claude.',
        author: { name: 'InventArch' },
      }),
    },
    { path: 'plugins/ia/agents/ia-author.md', text: AUTHOR },
    {
      path: 'plugins/ia/hooks/hooks.json',
      text: json({
        hooks: {
          SessionStart: [
            {
              matcher: 'startup|clear',
              hooks: [
                { type: 'command', command: 'node "${CLAUDE_PLUGIN_ROOT}/hooks/session-start.mjs"', timeout: 10 },
              ],
            },
          ],
        },
      }),
    },
    { path: 'plugins/ia/hooks/session-start.mjs', text: HOOK },
    {
      path: 'plugins/ia/ia-plugin.json',
      text: json({
        format: 'ia.claude-plugin.v1',
        cli: input.cliVersion,
        channel: input.channel,
        entry: input.entry,
        install: input.install,
      }),
    },
    { path: 'plugins/ia/skills/authoring/SKILL.md', text: AUTHORING },
    { path: 'plugins/ia/skills/doctor/SKILL.md', text: DOCTOR },
    { path: 'plugins/ia/skills/init/SKILL.md', text: INIT },
  ];
  return Object.freeze(files.map((file) => Object.freeze(file)));
}
