import type { CompiledRecord } from '@ia/language';
import { assess } from './types.js';
import type { Assessment } from './types.js';
import { cite, text } from './record-text.js';
export { cite, fieldText, governanceClauses, text } from './record-text.js';
export { LEGACY_STEWARD_TOOLS, REQUIRE_STEWARD_PROFILES, STEWARD_HOST_TABLE } from './steward-profile.js';

export const PROJECTION_MARKER = '<!-- Generated by tools/projections/generate.ts; edit the cited native records. -->';
export interface HostArtifact {
  readonly path: string;
  readonly text: string;
}
export interface HostArtifacts {
  readonly assessment: Assessment;
  readonly artifacts: readonly HostArtifact[];
}
/** Revision-bound physical membership supplied by an admitted-view composition root. */
export interface ProjectionMembership {
  readonly revision: string;
  readonly members: readonly { readonly path: string; readonly system: string | null; readonly root: string | null }[];
}
type Member = ProjectionMembership['members'][number];
/** One admitted non-floor system with its uniquely resolved, correctly rooted steward. */
export interface AdmittedSteward {
  readonly system: CompiledRecord;
  readonly member: Member;
  readonly agent: CompiledRecord;
}
export interface Admission {
  readonly byPath: ReadonlyMap<string, Member>;
  readonly systems: readonly AdmittedSteward[];
}
const word = /^[a-z][a-z0-9-]*$/;
export const invalidAssessment = (message: string): HostArtifacts =>
  Object.freeze({
    assessment: assess('COMP-PROJECTIONS', 'repository', [
      { code: 'IA-COMP-PROJECTION-INVALID', severity: 'error', path: '.ia/src/systems', line: 1, message },
    ]),
    artifacts: Object.freeze([]),
  });
/**
 * Spec §6.1: the refusal conditions every host renderer shares. Checks, in order: a fresh, matching revision;
 * a portable, non-aliased, correctly rooted membership covering every admitted source; unique record identities;
 * and, per admitted non-floor system, a single unfragmented steward ref resolving to a uniquely named agent
 * declared under that system's own membership root. Callers render artifacts from the returned admission.
 */
export function admittedStewards(
  records: readonly CompiledRecord[],
  revision: string,
  membership: ProjectionMembership,
): Admission | HostArtifacts {
  if (!revision.trim() || membership.revision !== revision)
    return invalidAssessment('Projection membership revision is stale');
  const sources = new Set(records.map((r) => r.source.path)),
    byPath = new Map<string, Member>(),
    aliases = new Set<string>();
  const portable = (path: string): boolean =>
    path === path.normalize('NFC') &&
    !/[\\\u0000-\u001f<>:"|?*]/.test(path) &&
    path
      .split('/')
      .every(
        (part) =>
          !!part &&
          part !== '.' &&
          part !== '..' &&
          !/[. ]$/.test(part) &&
          !/^(con|prn|aux|nul|com[0-9]|lpt[0-9])(?:\.|$)/i.test(part),
      );
  for (const member of membership.members) {
    const key = member.path.toLowerCase();
    if (!sources.has(member.path) || aliases.has(key) || !portable(member.path))
      return invalidAssessment('Invalid or conflicting projection membership');
    if (
      member.system === null
        ? member.root !== null
        : !word.test(member.system) ||
          member.root === null ||
          !portable(member.root) ||
          !member.root.endsWith('/' + member.system) ||
          !member.path.startsWith(member.root + '/')
    )
      return invalidAssessment('Invalid or conflicting projection membership');
    aliases.add(key);
    byPath.set(member.path, member);
  }
  if (records.some((r) => !byPath.has(r.source.path)))
    return invalidAssessment('Projection source membership is unavailable');
  const occurrences = new Set<string>();
  for (const record of records) {
    if (occurrences.has(record.identity))
      return invalidAssessment('Projection requires unique admitted record identities');
    occurrences.add(record.identity);
  }
  const systemRecords = records
    .filter((r) => r.discriminator === 'system' && !r.source.path.startsWith('.ia/src/floor/'))
    .sort((a, b) => (a.name < b.name ? -1 : 1));
  if (systemRecords.length === 0) return invalidAssessment('No admitted native systems');
  const names = new Set<string>(),
    systems: AdmittedSteward[] = [];
  for (const system of systemRecords) {
    const member = byPath.get(system.source.path);
    const refs = system.head.filter((f) => f.key === 'steward').map((f) => f.value),
      ref = refs.length === 1 ? refs[0] : undefined;
    const found =
      ref?.kind === 'ref' && ref.discriminator === 'agent' && ref.fragment === undefined
        ? records.filter(
            (r) =>
              r.discriminator === 'agent' && r.name === ref.name && byPath.get(r.source.path)?.system === system.name,
          )
        : [];
    const agent = found.length === 1 ? found[0] : undefined;
    if (
      !word.test(system.name) ||
      member?.system !== system.name ||
      system.source.path !== member.root + '/system.ia' ||
      agent === undefined ||
      !word.test(agent.name) ||
      names.has(agent.name)
    )
      return invalidAssessment(`Invalid or nonunique host steward for ${system.name}`);
    names.add(agent.name);
    systems.push({ system, member, agent });
  }
  return { byPath, systems };
}
export interface RenderOptions {
  /** Refuse a steward without an `@agent-profile`. Defaults to REQUIRE_STEWARD_PROFILES. */
  readonly requireStewardProfiles?: boolean;
}
/** C22: interpret admitted semantic products; no filesystem or source parser. */
export function renderHostArtifacts(
  records: readonly CompiledRecord[],
  revision: string,
  membership?: ProjectionMembership,
  _modes?: readonly { readonly invocation: string; readonly meaning: string }[],
  _options: RenderOptions = {},
): HostArtifacts {
  if (!revision.trim()) return invalidAssessment('Projection requires a corpus revision');
  // Legacy callers retain their authored-only contract. Adopted callers supply the
  // database's observations; this package neither discovers mounts nor imports db.
  const resolved: ProjectionMembership = membership ?? {
    revision,
    members: [...new Set(records.map((r) => r.source.path))].flatMap((path) => {
      const match = /^(\.ia\/src\/systems\/([a-z][a-z0-9-]*))\//.exec(path);
      return [{ path, system: match?.[2] ?? null, root: match?.[1] ?? null }];
    }),
  };
  const admitted = admittedStewards(records, revision, resolved);
  if ('artifacts' in admitted) return admitted;
  const { systems } = admitted;
  const artifacts: HostArtifact[] = [],
    rows: string[] = [];
  for (const { system, agent } of systems) {
    const meaning = agent.sections
      .filter((section) => section.name === 'meaning')
      .flatMap((section) => section.fields)
      .filter((field) => 'key' in field && field.key === 'says')
      .map((field) => ('value' in field ? text(field.value) : ''))
      .join('\n');
    const attribution = `${PROJECTION_MARKER}\n\nSource revision: ${revision}\n\nSources: ${cite(system)}; ${cite(agent)}.`;
    artifacts.push({
      path: `.claude/agents/${agent.name}.md`,
      text: `---\nname: ${agent.name}\ndescription: ${JSON.stringify('Language reference for ' + system.name)}\n---\n\n${attribution}\n\n${meaning}\n\nRead docs/reference/language/vocabulary.json for canonical words and schemas. Validate required fields and references. An admitted declaration does not prove execution or grant authority. Adopted source paths are immutable references.\n`,
    });
    rows.push(`- ${system.name}: ${cite(system)}; ${cite(agent)}.`);
  }
  artifacts.push({
    path: 'CLAUDE.md',
    text: `${PROJECTION_MARKER}\n\n# IA language\n\nSource revision: ${revision}\n\nRead docs/reference/language/README.md and vocabulary.json for language contracts.\n\n${rows.join('\n')}\n`,
  });
  const skill = `---\nname: ia-authoring\ndescription: Author records against the public IA language contracts.\n---\n\n${PROJECTION_MARKER}\n\nRead docs/reference/language/README.md and vocabulary.json. Select the word matching the intended representation, satisfy its canonical schema, and validate references. Execution requires a separately supplied evaluator or host.\n`;
  for (const host of ['.agents', '.claude'])
    artifacts.push({ path: `${host}/skills/ia-authoring/SKILL.md`, text: skill });
  return Object.freeze({
    assessment: assess('COMP-PROJECTIONS', 'repository', []),
    artifacts: Object.freeze(artifacts.map((artifact) => Object.freeze(artifact))),
  });
}
