import type { CompiledRecord } from '@inventarch/language';
import { assess } from './types.js';
import { admittedStewards, cite, governanceClauses, invalidAssessment } from './projections.js';
import { says } from './record-text.js';
import type { HostArtifact, HostArtifacts, ProjectionMembership } from './projections.js';

export const WORKSPACE_PROJECTION_MARKER = '<!-- Generated by ia host; edit the cited native records. -->';
export interface WorkspaceProjectionInput {
  readonly host: 'claude' | 'codex';
  /** HOST_MODES rows from @inventarch/distribution/host-modes, rendered with the literal `<cache>` placeholder. */
  readonly modes: readonly { readonly invocation: string; readonly meaning: string }[];
  readonly distributions: readonly { readonly id: string; readonly version: string }[];
  readonly operations: readonly string[];
}
/**
 * Spec §6.1: systems, stewards, distributions, door, launcher modes. No named procedure is required.
 * Shares every refusal condition with renderHostArtifacts through admittedStewards (projections.ts).
 */
export function renderWorkspaceProjection(
  records: readonly CompiledRecord[],
  revision: string,
  membership: ProjectionMembership,
  input: WorkspaceProjectionInput,
): HostArtifacts {
  const admitted = admittedStewards(records, revision, membership);
  if ('artifacts' in admitted) return admitted;
  const rows: string[] = [],
    agents: HostArtifact[] = [];
  for (const { system, member, agent } of admitted.systems) {
    rows.push(`- ${system.name}: steward ${agent.name}; ${cite(system)}; ${cite(agent)}.`);
    // Host plugin distribution spec §10 (amends M5.3 §6.2): a steward follows its system into the workspace, authored
    // or installed; admittedStewards already excludes the floor, so every file here has records to ground on.
    if (input.host === 'claude') {
      // A list-form (block) clause renders as bullets; an empty clause is refused, as in renderHostArtifacts.
      const rendered = governanceClauses(agent, ['applies', 'requires']);
      if (!rendered.ok) return invalidAssessment(`Steward ${agent.name}: empty ${rendered.key} clause`);
      const clauses = rendered.text;
      // C24, as projections.ts marks adopted sources: a steward whose system is installed or adopted cannot repair its
      // definitions (the steward guard refuses those paths), so it reviews them and authors only local contributions.
      const local = member.root === `.ia/src/systems/${system.name}`;
      const description = local
        ? `Use for authoring, reviewing or repairing records owned by ${system.name}.`
        : `Use for reviewing records owned by ${system.name} and for authoring its permitted local contributions.`;
      const immutable = local
        ? ''
        : '\nInstalled or adopted definition sources are immutable. Author permitted project contributions in the local system folder; do not edit the cited source paths.\n';
      agents.push({
        path: `.claude/agents/${agent.name}.md`,
        text: `---\nname: ${agent.name}\ndescription: ${JSON.stringify(description)}\n---\n\n${WORKSPACE_PROJECTION_MARKER}\n\nSource revision: ${revision}\n\nSources: ${cite(system)}; ${cite(agent)}.\n\n# ${agent.name}\n\n${says(agent)}\n${clauses ? '\n' + clauses + '\n' : ''}${immutable}`,
      });
    }
  }
  const distributions = input.distributions.length
    ? input.distributions
        .slice()
        .sort((a, b) => (a.id < b.id ? -1 : 1))
        .map((d) => `- ${d.id} ${d.version}`)
        .join('\n')
    : '- none';
  const modes = input.modes.map((m) => `- \`${m.invocation}\`: ${m.meaning}`).join('\n');
  // Operator decision 2026-09-23: Claude is the host that registers the steward guard; the sentence states its rule, not that it ran.
  const guard =
    input.host === 'claude'
      ? `\n\nWhen the steward guard is registered, edits under .ia/src/systems/<name>/ are accepted only from that system's steward subagent.`
      : '';
  const instructions = `${WORKSPACE_PROJECTION_MARKER}\n\n# IA workspace\n\nSource revision: ${revision}\n\n## Systems and stewards\n\n${rows.join('\n')}${guard}\n\n## Installed distributions\n\n${distributions}\n\n## Reaching the door\n\nThe MCP server \`ia-workspace\` serves this workspace read-only. For one-shot queries run \`ia <operation> --root <workspace>\`, where the operation is one of: ${input.operations.join(', ')}.\n\n## Launcher modes\n\n\`ia doctor\` reports the path of \`<cache>\`.\n\n${modes}\n\n\n## User-level state\n\n~/.ia is the user-level IA home, not a workspace; ia doctor reports it.\n\nThis file is a projection of records. Adding text to it creates no rule; rules are authored records.\n`;
  const skill = `---\nname: ia-authoring\ndescription: Author or review IA records in this workspace.\n---\n\n${WORKSPACE_PROJECTION_MARKER}\n\nSource revision: ${revision}\n\nFind a word and its schema with \`ia vocabulary <word> --schema\`. Check records with \`ia validate\`. Inspect an admitted record with \`ia inspect <identity>\`. Validation establishes conformance to the declared schemas, not design quality.\n`;
  const artifacts: HostArtifact[] =
    input.host === 'claude'
      ? [
          { path: '.claude/rules/ia-workspace.md', text: instructions },
          { path: '.claude/skills/ia-authoring/SKILL.md', text: skill },
          ...agents,
        ]
      : [
          { path: 'AGENTS.md', text: instructions },
          { path: '.agents/skills/ia-authoring/SKILL.md', text: skill },
        ];
  return Object.freeze({
    assessment: assess('COMP-PROJECTIONS', 'repository', []),
    artifacts: Object.freeze(artifacts.map((a) => Object.freeze(a))),
  });
}
