/** Shared host fixtures. Each isolated test file owns its temporary roots and cleanup. */
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { expect } from 'vitest';
import { applyGuardRegistration, planGuardRegistration } from '@inventarch/distribution/guard-registration';
import { materializeHostPayload, readHostPin } from '@inventarch/distribution/host-home';
import { json, sha256 } from '@inventarch/distribution/services';
import { quote } from '../src/render.js';
import { cli, run, scratch } from './workspace-fixture.js';

export const put = (root: string, path: string, text: string): void => {
  mkdirSync(dirname(resolve(root, path)), { recursive: true });
  writeFileSync(resolve(root, path), text);
};
export const read = (root: string, path: string): string => readFileSync(resolve(root, path), 'utf8');
/**
 * A workspace named `demo` as a default `ia init --apply` leaves it: the three starter records in
 * `.ia/src/workspace.ia` (`@workspace demo`, its participant `@agent demo` and `@mandate demo-mandate`), no local
 * system, and its capture.
 */
export async function initialized(): Promise<{ root: string; env: { IA_HOST_HOME: string } }> {
  const root = resolve(scratch('host'), 'demo'),
    env = { IA_HOST_HOME: scratch('host-home') };
  const result = await run(['init', root, '--apply', '--yes', '--json']);
  expect(result.exitCode, result.stdout).toBe(0);
  return { root, env };
}
export const host = (root: string, env: Record<string, string>, ...extra: string[]) =>
  run(['host', ...extra, '--root', root, '--json'], { env });
export const human = (root: string, env: Record<string, string>, ...extra: string[]) =>
  run(['host', ...extra, '--root', root], { env });
export const element = (envelope: any, id: string): any =>
  envelope.plan.elements.find((row: { id: string }) => row.id === id);

/** A pid no process holds: a child that has already exited. The lock a killed run leaves names one like it. */
export const deadPid = (): number =>
  spawnSync(process.execPath, ['-e', ''], { env: { ...process.env, NODE_OPTIONS: '' } }).pid!;
export const HOST_LOCK = '.ia/distributions/hosts/lock.json';
export const lockNext = (root: string): string =>
  `Another ia host run holds the host lock, or a killed run left it: run "ia recover host --root ${quote(root)}" (it clears a dead holder's lock and refuses a live one), then rerun.`;

export type Row = { id: string; status: string; detail: string; remedy: string | null };
export const doctor = async (root: string, env: Record<string, string>) => {
  const result = await run(['doctor', '--root', root, '--json'], { env });
  return { exitCode: result.exitCode, checks: JSON.parse(result.stdout).checks as Row[] };
};
export const row = (checks: readonly Row[], id: string): Row | undefined => checks.find((check) => check.id === id);
/**
 * Doctor's one projection row when it finds no drift (task ia-project-verb): every file the receipt lists is as
 * written and the records render the packet it names.
 */
export const noDrift = (name = 'claude') =>
  expect.objectContaining({ id: `projection-${name}`, status: 'ok', detail: expect.stringContaining('No drift: ') });
/** Doctor was given --root, so each command it prints carries it, in the form `ia init --host` uses (rootedNext). */
export const rootedApply = (root: string, name = 'claude'): string => `ia host ${name} --root ${quote(root)} --apply`;

/** The marker the 1.x `ia host` renderer wrote (compliance's retired WORKSPACE_PROJECTION_MARKER). */
export const LEGACY_MARKER = '<!-- Generated by ia host; edit the cited native records. -->';
export const GUARD_STATE = '.ia/distributions/hosts/claude-guard-workspace.json';
export const RECEIPT = '.ia/distributions/hosts/claude-receipt.json';
export const STEWARD = '.claude/agents/demo-steward.md';
/** The 1.x claude projection of the starter, each file with `ia host`'s 1.x marker. */
export const LEGACY_FILES: Readonly<Record<string, string>> = {
  '.claude/rules/ia-workspace.md': `${LEGACY_MARKER}\n\n# IA workspace\n\nSource revision: 1.x\n\n## Systems and stewards\n\n- demo: steward demo-steward.\n`,
  '.claude/skills/ia-authoring/SKILL.md': `---\nname: ia-authoring\ndescription: Author or review IA records in this workspace.\n---\n\n${LEGACY_MARKER}\n\nSource revision: 1.x\n`,
  [STEWARD]: `---\nname: demo-steward\ndescription: "Use for authoring, reviewing or repairing records owned by demo."\n---\n\n${LEGACY_MARKER}\n\nSource revision: 1.x\n\n# demo-steward\n\nOwns the demo system and its records.\n`,
};
/**
 * A workspace as a 1.x `ia host claude --apply` left it (milestone position-packet's upgrade fixture): the steward
 * guard registered by apps/distribution's own guard registration against the materialized payload — its group in
 * `.claude/settings.local.json` and `claude-guard-workspace.json` — and a projection state owning the 1.x rules file,
 * skill and `demo-steward.md`, each written with the 1.x marker. The payload is the one `ia host` materializes.
 */
export function legacyRegistration(root: string, env: { IA_HOST_HOME: string }): void {
  legacyGuard(root, env);
  for (const [path, text] of Object.entries(LEGACY_FILES)) put(root, path, text);
  put(
    root,
    '.ia/distributions/hosts/claude-projection.json',
    json({
      format: 'ia.host-projection-state.v1',
      host: 'claude',
      files: Object.fromEntries(Object.entries(LEGACY_FILES).map(([path, text]) => [path, sha256(text)])),
    }),
  );
}
/** The steward guard alone, as a 1.x `ia host claude --apply` registered it: its group and its ownership state. */
export function legacyGuard(root: string, env: { IA_HOST_HOME: string }): void {
  const bundled = readHostPin(cli),
    cache = materializeHostPayload({ home: env.IA_HOST_HOME, archive: bundled.archive(), pin: bundled.pin }).directory;
  applyGuardRegistration(planGuardRegistration(realpathSync(root), { cache }));
}
/** Whether `.claude/settings.local.json` still holds a steward-guard group. */
export const guardGroups = (root: string): number => {
  let text: string;
  try {
    text = read(root, '.claude/settings.local.json');
  } catch {
    return 0;
  }
  const groups = (JSON.parse(text) as { hooks?: { PreToolUse?: { matcher?: string }[] } }).hooks?.PreToolUse ?? [];
  return groups.filter((group) => group.matcher === 'Write|Edit|MultiEdit').length;
};
