import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { copy, digest } from '@inventarch/graph';
import { RuntimeError } from './errors.js';
import { entryCount } from './packet.js';
import type { PacketHostNote, PositionPacket } from './packet.js';
import type { ScopeKey } from './scope-key.js';
import { freeze } from './types.js';

/**
 * The host adapters: position-and-projection §4 (the host adapter contract) and items 11, 12 and 14; plan amendments
 * B9, B10 and B12 (milestone position-packet). `renderHost` renders one position packet (R19) for the claude or the
 * codex host as files that each carry the generated marker, and returns them with a receipt. It is a pure function of
 * its arguments and this package's version: it reads no workspace, writes and deletes no file, and renders no agent
 * file for any host (design §4: the N system stewards are pointer lines, never agent definitions).
 *
 * The entry file holds the packet's sections in the packet's field order, one entry per list item or table body row,
 * then the provenance line; a host changes only the path, so the sections are byte-identical for both hosts. Each bare
 * IA word token in free text is a code span (markup only), so no committed or consumer file renders a GitHub mention.
 * The one `ia-authoring` skill per host stays (B10) with its text as compliance's 1.x renderers wrote it, its marker
 * line aside.
 */

/** B9: the one marker the packet's files carry, first in an entry file and after a skill's YAML frontmatter. */
export const PACKET_MARKER = '<!-- Generated by ia project; edit the cited native records. -->';
export type PacketHost = 'claude' | 'codex';
/**
 * `repository`: the files this repository commits (decision packet-tracking-policy), which name the adapter without
 * its version and carry no host note, so neither a release nor a machine moves them; `consumer`: a consumer
 * workspace's machine-local files, which carry both.
 */
export type PacketTarget = 'repository' | 'consumer';
/** A rendered file: a workspace-relative, `/`-separated path and its text. */
export interface HostFile {
  readonly path: string;
  readonly text: string;
}
/**
 * B12: the receipt of one render, which the caller that applies the files writes beside the projection state.
 * `renderHost` fills what the render decides and leaves `removed` and `foreign` empty, `guard` `none`, and `cli` and
 * `writtenAt` null; the caller that writes and deletes the files sets those five (milestone position-packet task
 * replace-renderers).
 */
export interface PacketReceipt {
  readonly format: 'ia.packet-receipt.v1';
  readonly host: PacketHost;
  /** The applying CLI's `<id>@<version>` (design item 12), which only that caller knows. */
  readonly cli: string | null;
  /** `<adapter id>@<@inventarch/runtime version>`, `ia-claude@…` or `ia-codex@…`, in either target. */
  readonly adapter: string;
  /** The packet's revision. */
  readonly revision: string;
  /** The packet's provenance slug, null when it has none (decision identity-namespace: the slug lives here). */
  readonly slug: string | null;
  readonly packetDigest: string;
  /** The packet's `body`, the digest of body(K0). */
  readonly bodyDigest: string;
  /** entryCount(packet): the entries the entry file renders. */
  readonly entries: number;
  /** The files this render writes and expects to remain, in render order, each with the SHA-256 of its UTF-8 text. */
  readonly files: readonly { readonly path: string; readonly sha256: string }[];
  /** The owned legacy files the applying caller deleted (B9). */
  readonly removed: readonly { readonly path: string; readonly sha256: string }[];
  /** The unmarked files the applying caller left in place (design §4, adapter rule 2). */
  readonly foreign: readonly string[];
  /** Whether the applying caller retired a steward-guard registration first (B11). */
  readonly guard: 'retired' | 'none';
  readonly hostNote: PacketHostNote;
  /** The packet's participant identities (design item 14: whom its writes are attributed to). */
  readonly participants: readonly string[];
  /** The packet's mandate identities. */
  readonly mandates: readonly string[];
  /** When the applying caller wrote the files. */
  readonly writtenAt: string | null;
}
/** What renderHost returns: the files in render order, the entry file first, and the receipt of that render. */
export interface HostOutput {
  readonly files: readonly HostFile[];
  readonly receipt: PacketReceipt;
}

/** This package's version, read from its own manifest as the MCP door reads its own. */
const VERSION: string = (
  JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8')) as { version: string }
).version;
const ADAPTERS: Readonly<Record<PacketHost, string>> = { claude: 'ia-claude', codex: 'ia-codex' };
/**
 * The entry file and the `ia-authoring` skill paths each host renders per target. The repository target's are the
 * files this repository commits (CLAUDE.md and both skills, no steward agent); codex's are the same in both.
 */
const PATHS: Readonly<
  Record<PacketHost, Readonly<Record<PacketTarget, { readonly entry: string; readonly skills: readonly string[] }>>>
> = {
  claude: {
    repository: {
      entry: 'CLAUDE.md',
      skills: ['.claude/skills/ia-authoring/SKILL.md', '.agents/skills/ia-authoring/SKILL.md'],
    },
    consumer: { entry: '.claude/rules/ia-workspace.md', skills: ['.claude/skills/ia-authoring/SKILL.md'] },
  },
  codex: {
    repository: { entry: 'AGENTS.md', skills: ['.agents/skills/ia-authoring/SKILL.md'] },
    consumer: { entry: 'AGENTS.md', skills: ['.agents/skills/ia-authoring/SKILL.md'] },
  },
};
const TARGETS: readonly PacketTarget[] = ['repository', 'consumer'];
/**
 * The skill each target renders, the text compliance's two 1.x renderers wrote, the marker line aside: the
 * repository's (renderHostArtifacts) and a consumer workspace's (renderWorkspaceProjection), whichever host writes it.
 * Milestone position-packet task replace-renderers retired both renderers.
 */
const skill = (target: PacketTarget, revision: string): string =>
  target === 'repository'
    ? `---\nname: ia-authoring\ndescription: Author records against the public IA language contracts.\n---\n\n${PACKET_MARKER}\n\nRead docs/reference/language/README.md and vocabulary.json. Select the word matching the intended representation, satisfy its canonical schema, and validate references. Execution requires a separately supplied evaluator or host.\n`
    : `---\nname: ia-authoring\ndescription: Author or review IA records in this workspace.\n---\n\n${PACKET_MARKER}\n\nSource revision: ${revision}\n\nFind a word and its schema with \`ia vocabulary <word> --schema\`. Check records with \`ia validate\`. Inspect an admitted record with \`ia inspect <identity>\`. Validation establishes conformance to the declared schemas, not design quality.\n`;
const sha256 = (text: string): string => createHash('sha256').update(text, 'utf8').digest('hex');

/** `text` on one line: a line break and the blanks around it become one space, so each entry is one line. */
const inline = (text: string): string => text.replace(/[ \t]*(?:\r\n|\r|\n)\s*/g, ' ');
/** `text` as one code span: its fence one backtick longer than the longest run inside, padded where one touches it. */
function code(text: string): string {
  const one = inline(text),
    fence = '`'.repeat(Math.max(0, ...(one.match(/`+/g) ?? []).map((run) => run.length)) + 1),
    pad = one.startsWith('`') || one.endsWith('`') ? ' ' : '';
  return `${fence}${pad}${one}${pad}${fence}`;
}
/** An authored code span as CommonMark finds one: a whole backtick run, its text and the next run of the same length. */
const SPAN = /(?<!`)(`+)(?!`)[\s\S]*?(?<!`)\1(?!`)/g;
/**
 * A bare IA word token: `@` and a word as the language spells one, where no letter, digit, `_`, `.`, `-`, `/`, `@` or
 * backtick comes before it and no word character, `-`, `/`, `@` or backtick after it. An address (`a@b.c`), a scoped
 * package (`@inventarch/db`) and a token touching a backtick, which no fence could wrap without joining that run, are no
 * such token.
 */
const TOKEN = /(?<![\w.\-/@`])@[a-z][a-z0-9-]*(?![\w\-/@`])/;
/** An authored code span, matched first and kept as written, or else a bare IA word token. */
const SPAN_OR_TOKEN = new RegExp(`${SPAN.source}|${TOKEN.source}`, 'g');
/**
 * Free text on one line, each bare IA word token outside its authored code spans a code span, so no rendered file
 * shows `@workspace` or `@plan` as a GitHub mention. The token's fence is one backtick, or longer when the text holds a
 * backtick run no span closes: that run is literal text, and a fence of its length would close it. Markup only (design
 * §4): an authored span stays as written, a token in it included, and the packet's values and entries are unchanged.
 */
function prose(text: string): string {
  const one = inline(text),
    loose = new Set((one.replace(SPAN, '').match(/`+/g) ?? []).map((run) => run.length));
  let fence = '`';
  while (loose.has(fence.length)) fence += '`';
  return one.replace(SPAN_OR_TOKEN, (match, open?: string) =>
    open === undefined ? `${fence}${match}${fence}` : match,
  );
}
/** A list's items, comma-separated, or `none`. */
const list = (items: readonly string[], each: (item: string) => string = prose): string =>
  items.length === 0 ? 'none' : items.map(each).join(', ');
/** One table row, each cell on one line with its pipes escaped (GFM escapes them inside code spans too). */
const row = (cells: readonly string[]): string =>
  `| ${cells.map((cell) => inline(cell).replaceAll('|', '\\|')).join(' | ')} |`;
/** A table: its head, the delimiter row and one body row per entry; none while it has no entry. */
const table = (head: readonly string[], rows: readonly (readonly string[])[]): readonly string[] =>
  rows.length === 0 ? [] : [row(head), row(head.map(() => '---')), ...rows.map(row)];
/** The key used, as `ia position` prints it (a location seat `''` as `.`), on one line. */
const keyText = (key: ScopeKey): string =>
  [
    `seat ${key.seat === undefined ? "the repository's workspace" : inline(typeof key.seat === 'string' ? key.seat : key.seat.path || '.')}`,
    `shape ${key.shape}`,
    `phase ${key.phase}`,
    `depth ${key.depth}`,
    `budget ${key.budget}`,
    ...(key.word === undefined ? [] : [`word ${key.word}`]),
  ].join(', ');

/**
 * The packet's sections in its field order: the seat, participants, mandates, system pointer lines, captured-record
 * tallies, the intent and phase tables, the command catalog and the SPEC lines, under a title naming the provenance
 * slug. Each entry is one list item or table body row; a section with no entry renders no heading. `format`,
 * `revision` and `body` are no section: the provenance line's revision and packet digest cover them.
 */
function sections(packet: PositionPacket): readonly string[] {
  const out = [`# IA position packet${packet.provenance.slug === undefined ? '' : `: ${packet.provenance.slug}`}`];
  const section = (heading: string, lines: readonly string[]): void => {
    if (lines.length > 0) out.push('', `## ${heading}`, '', ...lines);
  };
  const { seat } = packet;
  section('Seat', [
    `- ${[
      `workspace ${seat.identity === undefined ? 'undeclared' : code(seat.identity)}`,
      `sources ${list(seat.sources, code)}`,
      `systems ${seat.systems}`,
      ...(seat.steward === undefined ? [] : [`steward ${code(seat.steward)}`]),
      ...(seat.participants === undefined ? [] : [`participants ${prose(seat.participants)}`]),
    ].join('; ')}`,
  ]);
  section(
    'Participants',
    packet.participants.map(
      ({ identity, says }) => `- ${code(identity)}${says === undefined ? '' : `: ${prose(says)}`}`,
    ),
  );
  section(
    'Mandates',
    packet.mandates.map(
      (mandate) =>
        `- ${code(mandate.identity)}: ${[
          `participant ${code(mandate.participant)}`,
          ...(mandate.moves === undefined ? [] : [`moves ${list(mandate.moves)}`]),
          `scope ${list(mandate.scope, code)}`,
          ...(mandate.excludedWords === undefined ? [] : [`excluded words ${list(mandate.excludedWords)}`]),
          ...(mandate.covers === undefined ? [] : [`covers ${list(mandate.covers, code)}`]),
        ].join('; ')}`,
    ),
  );
  section(
    'Systems',
    packet.systems.map(
      (system) =>
        `- ${code(system.identity)}: ${
          system.words === 'unresolved'
            ? 'words unresolved; steward unresolved'
            : [
                `words ${list(system.words)}`,
                `band ${system.band}`,
                ...(system.steward === undefined ? [] : [`steward ${code(system.steward)}`]),
                `reach ${code(system.reach)}`,
              ].join('; ')
        }`,
    ),
  );
  section(
    'Captured records',
    packet.tallies.map(({ word, count }) => `- ${word} ${count}`),
  );
  section(
    'Intent shapes',
    table(
      ['shape', 'category', 'primitive', 'phase', 'kinds', 'lanes', 'predicates', 'priming', 'words'],
      packet.intents.map((intent) => [
        prose(intent.shape),
        prose(intent.category),
        prose(intent.primitive),
        prose(intent.phase),
        list(intent.kinds),
        list(intent.lanes),
        list(intent.predicates),
        list(intent.priming),
        list(intent.words),
      ]),
    ),
  );
  section(
    'Phases',
    table(
      ['phase', 'primitives', 'what --phase changes'],
      packet.phases.map((phase) => [prose(phase.phase), list(phase.primitives), prose(phase.changes)]),
    ),
  );
  section(
    'Commands',
    table(
      ['command', 'mode', 'move', 'refuses', 'next'],
      packet.commands.map((command) => [
        code(command.command),
        prose(command.mode),
        prose(command.move),
        prose(command.refuses),
        code(command.next),
      ]),
    ),
  );
  section(
    'SPEC lines',
    packet.lines.map((line) => `- ${prose(line)}`),
  );
  return out;
}

/**
 * R20: the files the `host` adapter renders for `target` from the packet renderPacket returned with its digest and
 * host note, and the receipt of that render. No agent file is rendered for any host (B10): claude's consumer files are
 * `.claude/rules/ia-workspace.md` and `.claude/skills/ia-authoring/SKILL.md`, its repository files `CLAUDE.md` and
 * both skills; codex's are `AGENTS.md` and `.agents/skills/ia-authoring/SKILL.md` in either target. The entry file is
 * the marker, the packet's sections, the provenance line `ia-generated <revision> <packet digest> <adapter>` (the
 * adapter's version only in the consumer target) and, in the consumer target alone, the host note. An unknown host or
 * target, or a digest that is not the packet's, is IA-RUNTIME-REQUEST-INVALID.
 */
export function renderHost(
  host: PacketHost,
  packet: PositionPacket,
  packetDigest: string,
  hostNote: PacketHostNote,
  target: PacketTarget,
): HostOutput {
  if (!Object.hasOwn(ADAPTERS, host)) throw new RuntimeError('IA-RUNTIME-REQUEST-INVALID', `Unknown host: ${host}`);
  if (!TARGETS.includes(target))
    throw new RuntimeError('IA-RUNTIME-REQUEST-INVALID', `Unknown projection target: ${target}`);
  if (digest(packet) !== packetDigest)
    throw new RuntimeError('IA-RUNTIME-REQUEST-INVALID', 'The digest is not the digest of the packet');
  const adapter = `${ADAPTERS[host]}@${VERSION}`,
    paths = PATHS[host][target],
    consumer = target === 'consumer';
  const entry = [
    PACKET_MARKER,
    '',
    ...sections(packet),
    '',
    `ia-generated ${packet.provenance.revision} ${packetDigest} ${consumer ? adapter : ADAPTERS[host]}`,
    ...(consumer
      ? [
          '',
          '## Host note (not part of the packet)',
          '',
          `- freshness ${hostNote.freshness}`,
          `- installed ${hostNote.installed}`,
          `- key ${prose(keyText(hostNote.key))}`,
        ]
      : []),
  ].join('\n');
  const files: HostFile[] = [
    { path: paths.entry, text: `${entry}\n` },
    ...paths.skills.map((path) => ({ path, text: skill(target, packet.revision) })),
  ];
  const receipt: PacketReceipt = {
    format: 'ia.packet-receipt.v1',
    host,
    cli: null,
    adapter,
    revision: packet.revision,
    slug: packet.provenance.slug ?? null,
    packetDigest,
    bodyDigest: packet.body,
    entries: entryCount(packet),
    files: files.map(({ path, text }) => ({ path, sha256: sha256(text) })),
    removed: [],
    foreign: [],
    guard: 'none',
    // A copy: the output is frozen whole, and the caller's note is not this render's to freeze.
    hostNote: copy(hostNote),
    participants: packet.participants.map((participant) => participant.identity),
    mandates: packet.mandates.map((mandate) => mandate.identity),
    writtenAt: null,
  };
  return freeze({ files, receipt });
}
