import { spawnSync } from 'node:child_process';
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { afterEach, expect, it, vi } from 'vitest';
import { open } from '../../packages/db/src/index.js';
import { entryCount, renderPacket } from '../../packages/runtime/src/packet.js';
import { PACKET_MARKER } from '../../packages/runtime/src/packet-host.js';
import { packetCatalog } from '../../apps/cli/src/commands.js';
import { guardGroup } from '../../apps/distribution/src/guard-registration.js';
import { json } from '../../apps/distribution/src/files.js';
import { editJson, presentJson } from '../../apps/distribution/src/json-edit.js';
import { GUARD_SETTINGS, generateProjections, publishArtifacts, renderProjections } from './generate.js';

vi.mock('node:fs', async (importOriginal) => {
  const actual = await importOriginal<typeof import('node:fs')>();
  return { ...actual, unlinkSync: vi.fn(actual.unlinkSync) };
});

// Milestone position-packet task replace-renderers: this repository's committed projection is the position packet,
// rendered by the claude adapter for the repository target; a 1.x steward file or steward-guard registration is stale.
const root = resolve(import.meta.dirname, '../..'),
  temporary: string[] = [];
const FILES = ['CLAUDE.md', '.claude/skills/ia-authoring/SKILL.md', '.agents/skills/ia-authoring/SKILL.md'];
/** The two markers the 1.x renderers wrote (B9): this repository's and `ia host`'s. */
const REPO_MARK = '<!-- Generated by tools/projections/generate.ts; edit the cited native records. -->',
  HOST_MARK = '<!-- Generated by ia host; edit the cited native records. -->';
const GUARD_STATE = '.ia/distributions/hosts/claude-guard-workspace.json';
// Exact bytes from the M4 baseline e83a5dd72cb10b4361e0323f122cd2a532bde002, not an invented marked file.
const LEGACY_AGENT = '.claude/agents/public-governance-system-steward.md',
  LEGACY_TEXT = readFileSync(resolve(import.meta.dirname, 'fixtures/m4-governance-steward.txt'), 'utf8').replaceAll(
    '\r\n',
    '\n',
  );
function temp(): string {
  const path = mkdtempSync(resolve(tmpdir(), 'ia-projection-tests-'));
  temporary.push(path);
  return path;
}
afterEach(() => {
  for (const path of temporary.splice(0)) {
    const rel = relative(tmpdir(), path);
    if (isAbsolute(rel) || !rel.startsWith('ia-projection-tests-') || rel.includes('..'))
      throw new Error('Unsafe cleanup');
    rmSync(path, { recursive: true, force: true });
  }
  // A copied native corpus is hundreds of files, slow to delete on a loaded machine.
}, 60_000);
const put = (base: string, path: string, text: string): void => {
  mkdirSync(dirname(resolve(base, path)), { recursive: true });
  writeFileSync(resolve(base, path), text);
};
const read = (base: string, path: string): string => readFileSync(resolve(base, path), 'utf8');
/** A copy of this repository's native corpus, the layout the generator reads, with no projection file yet. */
function copy(): string {
  const base = temp();
  cpSync(resolve(root, '.ia/src'), resolve(base, '.ia/src'), { recursive: true });
  return base;
}
/**
 * A steward-guard registration as a 1.x `ia host` wrote it over an existing `settings` file: the group
 * guard-registration derives for this root appended to its PreToolUse array in place, and the ownership state its
 * planner records, the containers that were already there kept as `existing`. A removal never reads the cache.
 */
function registerGuard(base: string, settings: string): string {
  const real = realpathSync(base),
    cache = temp(),
    group = guardGroup(join(cache, 'scripts/ia.mjs'), real),
    existing = presentJson(settings, [['hooks'], ['hooks', 'PreToolUse']]);
  const text = editJson(settings, ['hooks', 'PreToolUse', -1], group, existing);
  put(base, GUARD_SETTINGS, text);
  put(
    base,
    GUARD_STATE,
    json({
      format: 'ia.guard-registration-state.v1',
      id: 'workspace',
      cache,
      release: 'a'.repeat(64),
      created: false,
      group,
      ...(existing.length === 0 ? {} : { existing }),
    }),
  );
  return text;
}
/** A token GitHub would render as a mention: a bare `@<word>` outside every code span. */
const bare = (text: string): readonly string[] =>
  text.replace(/(`+)[\s\S]*?(?<!`)\1(?!`)/g, '').match(/(?<![\w.\-/@`])@[a-z][a-z0-9-]*(?![\w\-/@])/g) ?? [];

it('renders this repository as its position packet: CLAUDE.md and both skills, no steward agent, as committed', () => {
  const files = renderProjections(root);
  expect(files.map((file) => file.path)).toEqual(FILES);
  for (const file of files) {
    expect(file.text.split('\n'), file.path).toContain(PACKET_MARKER);
    expect(file.text, file.path).toBe(read(root, file.path));
  }
  const claude = files[0]!.text;
  expect(claude.startsWith(`${PACKET_MARKER}\n\n# IA position packet: language-workspace\n`)).toBe(true);
  // One participant entry (plan task self-host-participant-records), and no host note in a committed file.
  const participants = claude.split('## Participants\n\n')[1]!.split('\n\n')[0]!.split('\n');
  expect(participants).toEqual([
    '- `agent-system/binding/agent/language-participant`: The IDE agent operating in the language workspace, any vendor.',
  ]);
  expect(claude).not.toContain('Host note');
  // Plan amendment B1 with the milestone's final catalog (C = 7, task ia-project-verb): 1 participant, 1 mandate, the
  // seat, 11 system lines, 22 tallies, 5 intent rows, 4 phase rows, 7 commands, provenance and 3 SPEC lines. The file
  // renders one entry per list item and table row, and the provenance line.
  const db = open(root, { cache: false });
  try {
    const { packet } = renderPacket(db, db.resolveScope().token, packetCatalog());
    expect(
      [packet.participants, packet.mandates, packet.systems, packet.tallies, packet.commands].map(
        (rows) => rows.length,
      ),
    ).toEqual([1, 1, 11, 22, 7]);
    expect(entryCount(packet)).toBe(56);
  } finally {
    db.close();
  }
  const lines = claude.split('\n'),
    rows = lines.filter(
      (line, index) => line.startsWith('| ') && !line.startsWith('| ---') && !lines[index + 1]?.startsWith('| ---'),
    );
  expect(lines.filter((line) => line.startsWith('- ') || line.startsWith('ia-generated ')).length + rows.length).toBe(
    56,
  );
  expect(rows).toContain(
    '| `ia project` | effect | Execution | a file without the generated marker at a path it writes, which its plan names; --apply writes nothing | `ia project <host>` |',
  );
  expect(rows).toContain(
    '| `ia capture` | effect | Execution | an uninitialized root with no authored `@workspace` and no source errors; nothing is written | `ia init <directory>` |',
  );
  // GitHub renders the committed file: every IA word in it is a code span, never a mention.
  expect(claude).toContain('`@workspace`');
  expect(bare(claude)).toEqual([]);
  // The tree holds no marked steward agent and no guard registration: the check finds nothing to do.
  expect(generateProjections(root, false)).toEqual([]);
  const base = temp();
  expect(publishArtifacts(base, files, false)).toEqual(FILES);
  publishArtifacts(base, files, true);
  expect(publishArtifacts(base, files, false)).toEqual([]);
});
it('commits CLAUDE.md and both skills, and ignores .claude/agents, where no file is tracked (packet-tracking-policy)', () => {
  // Milestone position-packet task untrack-steward-agents: no steward agent is tracked, and none can be added unforced.
  const base = temp(),
    empty = resolve(base, 'empty'),
    scratch = resolve(base, 'repository'),
    agent = '.claude/agents/public-work-system-steward.md';
  writeFileSync(empty, '');
  const git = (cwd: string, env: NodeJS.ProcessEnv, ...args: string[]): string[] => {
    const run = spawnSync('git', args, { cwd, encoding: 'utf8', timeout: 15000, env });
    expect(run.status, run.stderr).toBe(0);
    return run.stdout.split('\n').filter(Boolean);
  };
  // This checkout's index is read with the contributor's own Git environment: ls-files reads no ignore rule, and Git
  // honours a safe.directory only from system, global or command configuration.
  const tracked = (...paths: string[]): string[] => git(root, process.env, 'ls-files', '--', ...paths);
  expect(tracked(...FILES, '.claude/agents').sort()).toEqual([...FILES].sort());
  // The ignore check runs in a repository made without a template, so without an info/exclude, holding copies of the
  // tracked ignore files. Its Git has no inherited GIT_* variable, no system or global configuration and an empty
  // excludes file, so a contributor's own ignore rules can neither hide a tracked file nor stand in for the tracked
  // rule. --no-index matches each path, tracked or not, and -v names the rule behind each ignored path.
  const isolated = {
    ...Object.fromEntries(Object.entries(process.env).filter(([name]) => !name.startsWith('GIT_'))),
    GIT_CONFIG_NOSYSTEM: '1',
    GIT_CONFIG_GLOBAL: empty,
  };
  const ignores = (cwd: string, ...args: string[]): string[] =>
    git(cwd, isolated, '-c', `core.excludesFile=${empty}`, ...args);
  ignores(base, 'init', '--quiet', '--template=', scratch);
  for (const path of tracked(':(glob)**/.gitignore')) put(scratch, path, read(root, path));
  const rule = read(root, '.gitignore').split(/\r?\n/).indexOf('/.claude/agents/') + 1;
  expect(rule).toBeGreaterThan(0);
  expect(ignores(scratch, 'check-ignore', '-v', '--no-index', '--', ...FILES, agent)).toEqual([
    `.gitignore:${rule}:/.claude/agents/\t${agent}`,
  ]);
});
it('checks without writing, publishes changed bytes and leaves equal bytes untouched', () => {
  const base = temp(),
    artifact = { path: 'CLAUDE.md', text: PACKET_MARKER + '\nfirst\n' };
  expect(publishArtifacts(base, [artifact], false)).toEqual(['CLAUDE.md']);
  expect(publishArtifacts(base, [artifact], true)).toEqual(['CLAUDE.md']);
  const time = statSync(resolve(base, 'CLAUDE.md')).mtimeMs;
  expect(publishArtifacts(base, [artifact], true)).toEqual([]);
  expect(statSync(resolve(base, 'CLAUDE.md')).mtimeMs).toBe(time);
  const changed = { ...artifact, text: PACKET_MARKER + '\nsecond\n' };
  expect(publishArtifacts(base, [changed], true)).toEqual(['CLAUDE.md']);
  expect(read(base, 'CLAUDE.md')).toBe(changed.text);
  // A file a 1.x renderer marked is owned, so it is replaced rather than refused.
  put(base, 'CLAUDE.md', `${REPO_MARK}\n\n# IA language\n`);
  expect(publishArtifacts(base, [changed], true)).toEqual(['CLAUDE.md']);
  expect(read(base, 'CLAUDE.md')).toBe(changed.text);
});
it('preflights unmanaged files before writing and refuses arbitrary outputs, steward agents and aliases', () => {
  const base = temp(),
    outside = temp();
  writeFileSync(resolve(base, 'CLAUDE.md'), 'User-authored');
  const first = { path: '.claude/skills/ia-authoring/SKILL.md', text: PACKET_MARKER },
    last = { path: 'CLAUDE.md', text: PACKET_MARKER };
  // Design row 27: the refusal names the file to delete and the one command that follows.
  expect(() => publishArtifacts(base, [first, last], true)).toThrow(
    'Refusing unmanaged projection: CLAUDE.md; delete CLAUDE.md, then run "pnpm projections:generate"',
  );
  expect(() => statSync(resolve(base, first.path))).toThrow();
  for (const path of ['../escape', '.claude/agents/fresh.md', '.claude/skills/ia-authoring/parts/orient.md'])
    expect(() => publishArtifacts(base, [{ path, text: PACKET_MARKER }], true), path).toThrow('output set');
  symlinkSync(outside, resolve(base, '.agents'), 'junction');
  expect(() =>
    publishArtifacts(base, [{ path: '.agents/skills/ia-authoring/SKILL.md', text: PACKET_MARKER }], true),
  ).toThrow('aliased');
});
it.each(['LF', 'CRLF'])('deletes only an exact M4 steward at its original path (%s)', (ending) => {
  const base = temp(),
    files = [{ path: 'CLAUDE.md', text: `${PACKET_MARKER}\n` }],
    legacy = ending === 'LF' ? LEGACY_TEXT : LEGACY_TEXT.replaceAll('\n', '\r\n');
  put(base, LEGACY_AGENT, legacy);
  const foreign = {
    '.claude/agents/mine.md': 'my own agent\n',
    '.claude/agents/my-reviewer.md': LEGACY_TEXT.replace('name: public-governance-system-steward', 'name: my-reviewer'),
    '.claude/agents/copied-steward.md': LEGACY_TEXT,
    '.claude/agents/notes.txt': `Scratch notes\n${REPO_MARK}\n${PACKET_MARKER}\nkeep me\n`,
    '.claude/agents/new-packet.md': `${PACKET_MARKER}\nkeep me\n`,
    '.claude/agents/quoted-marker.md': `A personal note quoting the legacy marker:\n${HOST_MARK}\nkeep me\n`,
    '.claude/agents/older-steward.md': `---\nname: older-steward\n---\n\n${REPO_MARK}\n`,
  };
  for (const [path, content] of Object.entries(foreign)) put(base, path, content);
  expect(publishArtifacts(base, files, false)).toEqual([LEGACY_AGENT, 'CLAUDE.md']);
  expect(read(base, LEGACY_AGENT)).toBe(legacy);
  expect(publishArtifacts(base, files, true)).toEqual([LEGACY_AGENT, 'CLAUDE.md']);
  expect(existsSync(resolve(base, LEGACY_AGENT))).toBe(false);
  for (const [path, content] of Object.entries(foreign)) expect(read(base, path), path).toBe(content);
  expect(publishArtifacts(base, files, false)).toEqual([]);
});
it.each([
  ['appended personal notes', LEGACY_TEXT + '\nPersonal notes: keep these.\n'],
  ['new packet marker', LEGACY_TEXT.replace(REPO_MARK, PACKET_MARKER)],
  ['quoted legacy marker', 'Personal notes\n' + LEGACY_TEXT],
  ['edited source revision', LEGACY_TEXT.replace('Source revision:', 'Previous revision:')],
  ['mixed line endings', LEGACY_TEXT.replace('\n', '\r\n')],
])('preserves a known steward path with %s', (_case, content) => {
  const base = temp();
  put(base, LEGACY_AGENT, content);
  expect(publishArtifacts(base, [], false)).toEqual([]);
  expect(publishArtifacts(base, [], true)).toEqual([]);
  expect(read(base, LEGACY_AGENT)).toBe(content);
});
it('retires the guard before the first stale-agent unlink fails, and resumes without losing foreign files', async () => {
  const base = temp(),
    permissions = '{\n  "permissions": {"allow": ["Read"]},\n  "hooks": {"PreToolUse": []}\n}\n',
    foreign = '.claude/agents/my-reviewer.md',
    files = [{ path: 'CLAUDE.md', text: `${PACKET_MARKER}\n` }];
  put(base, LEGACY_AGENT, LEGACY_TEXT);
  put(base, foreign, LEGACY_TEXT);
  registerGuard(base, permissions);
  const actual = await vi.importActual<typeof import('node:fs')>('node:fs'),
    failure = Object.assign(new Error('injected locked stale agent'), {
      code: 'EPERM',
      path: resolve(base, LEGACY_AGENT),
    }),
    attempts: string[] = [];
  vi.mocked(unlinkSync).mockImplementation((target) => {
    if (String(target) === resolve(base, LEGACY_AGENT)) {
      attempts.push(String(target));
      throw failure;
    }
    actual.unlinkSync(target);
  });
  try {
    expect(() => publishArtifacts(base, files, true)).toThrow(failure);
    expect(attempts).toEqual([resolve(base, LEGACY_AGENT)]);
    // This is observed after the FIRST attempted agent unlink, before any packet publication or retry.
    // Moving applyGuardRegistration below the stale loop leaves both guard assertions failing.
    expect(existsSync(resolve(base, GUARD_STATE))).toBe(false);
    expect(read(base, GUARD_SETTINGS)).toBe(permissions);
    expect(read(base, LEGACY_AGENT)).toBe(LEGACY_TEXT);
    expect(read(base, foreign)).toBe(LEGACY_TEXT);
    expect(existsSync(resolve(base, 'CLAUDE.md'))).toBe(false);
  } finally {
    vi.mocked(unlinkSync).mockImplementation(actual.unlinkSync);
  }
  expect(publishArtifacts(base, files, true)).toEqual([LEGACY_AGENT, 'CLAUDE.md']);
  expect(read(base, foreign)).toBe(LEGACY_TEXT);
  expect(publishArtifacts(base, files, false)).toEqual([]);
});
it('upgrades a copy of this repository: retires an owned guard group before deleting a 1.x steward file (B11)', () => {
  const base = copy(),
    agent = LEGACY_AGENT,
    legacy = LEGACY_TEXT,
    permissions =
      '{\n  "permissions": {\n    "allow": [\n      "Read"\n    ]\n  },\n  "hooks": {\n    "PreToolUse": []\n  }\n}\n';
  put(base, agent, legacy);
  const settings = registerGuard(base, permissions);
  // The check reports both, and writes nothing.
  expect(generateProjections(base, false)).toEqual([GUARD_SETTINGS, agent, ...FILES]);
  expect(read(base, GUARD_SETTINGS)).toBe(settings);
  expect(read(base, agent)).toBe(legacy);
  // The write retires the guard through apps/distribution's guard registration, deletes the steward file and
  // renders the packet; the settings file is byte for byte what it was before the registration, every other key and
  // the containers that were already there kept.
  expect(settings).not.toBe(permissions);
  expect(generateProjections(base, true)).toEqual([GUARD_SETTINGS, agent, ...FILES]);
  expect(existsSync(resolve(base, GUARD_STATE))).toBe(false);
  expect(existsSync(resolve(base, agent))).toBe(false);
  expect(read(base, GUARD_SETTINGS)).toBe(permissions);
  for (const path of FILES) expect(read(base, path).split('\n'), path).toContain(PACKET_MARKER);
  expect(generateProjections(base, false)).toEqual([]);
  // Copying the native corpus (hundreds of files) and deleting it again dominate this test: allow for a loaded machine.
}, 180_000);
it('refuses a guard registration it cannot retire, naming the repair, before changing anything', () => {
  const base = temp(),
    agent = LEGACY_AGENT;
  put(base, agent, LEGACY_TEXT);
  registerGuard(base, '{\n  "hooks": {\n    "PreToolUse": []\n  }\n}\n');
  // The group changed by hand: the retirement refuses it, so the check and the write both stop.
  const changed = JSON.parse(read(base, GUARD_SETTINGS));
  changed.hooks.PreToolUse[0].timeout = 99;
  put(base, GUARD_SETTINGS, JSON.stringify(changed, null, 2) + '\n');
  for (const write of [false, true])
    expect(() => publishArtifacts(base, [{ path: 'CLAUDE.md', text: PACKET_MARKER }], write)).toThrow(
      `; remove only the unmatched IA guard group in ${GUARD_SETTINGS}, then run "pnpm projections:generate"`,
    );
  expect(existsSync(resolve(base, agent))).toBe(true);
  expect(existsSync(resolve(base, GUARD_STATE))).toBe(true);
  expect(existsSync(resolve(base, 'CLAUDE.md'))).toBe(false);
});
it.each([
  [GUARD_SETTINGS, false],
  ['.claude/settings.json', false],
  ['.claude/settings.json', true],
] as const)(
  'refuses an unmatched guard in %s (owned state: %s) before deleting stewards',
  (settingsPath, ownedState) => {
    const base = temp(),
      permissions = '{\n  "permissions": {"allow": ["Read"]},\n  "hooks": {"PreToolUse": []}\n}\n',
      files = [{ path: 'CLAUDE.md', text: `${PACKET_MARKER}\n` }];
    put(base, LEGACY_AGENT, LEGACY_TEXT);
    const guarded = registerGuard(base, permissions);
    if (!ownedState) rmSync(resolve(base, GUARD_STATE));
    if (settingsPath !== GUARD_SETTINGS) {
      put(base, settingsPath, guarded);
      if (!ownedState) put(base, GUARD_SETTINGS, permissions);
    }
    const beforeLocal = read(base, GUARD_SETTINGS),
      beforeState = ownedState ? read(base, GUARD_STATE) : null;
    for (const write of [false, true]) {
      expect(() => publishArtifacts(base, files, write)).toThrow(
        `; remove only the unmatched IA guard group in ${settingsPath}, then run "pnpm projections:generate"`,
      );
      expect(read(base, settingsPath)).toBe(guarded);
      expect(read(base, GUARD_SETTINGS)).toBe(beforeLocal);
      expect(ownedState ? read(base, GUARD_STATE) : null).toBe(beforeState);
      expect(read(base, LEGACY_AGENT)).toBe(LEGACY_TEXT);
      expect(existsSync(resolve(base, 'CLAUDE.md'))).toBe(false);
    }
    // Follow the exact manual repair: remove only the unmatched group, preserving every other setting.
    put(base, settingsPath, permissions);
    expect(publishArtifacts(base, files, true)).toEqual([
      ...(ownedState ? [GUARD_SETTINGS] : []),
      LEGACY_AGENT,
      'CLAUDE.md',
    ]);
    expect(read(base, settingsPath)).toBe(permissions);
    expect(existsSync(resolve(base, GUARD_STATE))).toBe(false);
    expect(existsSync(resolve(base, LEGACY_AGENT))).toBe(false);
  },
);
it('refuses generating a partial corpus with admission errors, naming the command that prints them', () => {
  expect(() => generateProjections(resolve(root, 'packages/compliance/fixtures/loop'), false)).toThrow(
    'Native corpus has errors; projections refused; run "pnpm native:check" for the findings',
  );
});

it('names one next command in every refusal the generator raises (design row 27)', () => {
  // Every construction site in the source, so a refusal added later without a next command fails here.
  const source = readFileSync(resolve(import.meta.dirname, 'generate.ts'), 'utf8');
  const messages = [...source.matchAll(/throw new Error\(\s*`([^`]*)`/g)].map((match) => match[1]!);
  expect(source.match(/throw new Error\(/g)).toHaveLength(messages.length);
  expect(messages).toHaveLength(10);
  for (const message of messages)
    expect(message.match(/\$\{(?:GENERATE|SHOW_FINDINGS|SHOW_RENDERER)\}/g), message).toHaveLength(1);
});
it('names the next command for a usage refusal of the generator run as a program', () => {
  const result = spawnSync(
    process.execPath,
    ['--conditions=development', '--import', 'tsx', resolve(import.meta.dirname, 'generate.ts')],
    { cwd: root, encoding: 'utf8', timeout: 15000 },
  );
  expect(result.status, result.stderr).toBe(1);
  expect(result.stdout).toBe('');
  expect(result.stderr.split(/\r?\n/)).toContain('Usage: generate.ts --check|--write; run "pnpm projections:generate"');
});
