import { createHash, randomUUID } from 'node:crypto';
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  realpathSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, isAbsolute, relative, resolve, sep } from 'node:path';
import { isEntry } from '../entry/is-entry.mjs';
import { open, unaliased } from '../../packages/db/src/index.js';
import { renderPacket } from '../../packages/runtime/src/packet.js';
import { PACKET_MARKER, renderHost } from '../../packages/runtime/src/packet-host.js';
import type { HostFile } from '../../packages/runtime/src/packet-host.js';
import { packetCatalog } from '../../apps/cli/src/commands.js';
import { applyGuardRegistration, planGuardRegistration } from '../../apps/distribution/src/guard-registration.js';
import type { GuardPlan } from '../../apps/distribution/src/guard-registration.js';
import { HOST_REGISTRATION } from '../../apps/distribution/src/host.js';
import { LEGACY_STEWARDS } from './legacy-stewards.js';

/**
 * This repository's committed projection (decision packet-tracking-policy; milestone position-packet task
 * replace-renderers): the position packet of its own records, rendered by the claude adapter for the repository target
 * (`CLAUDE.md` and the two `ia-authoring` skills). No per-system steward agent is rendered any more (design §4); a
 * steward file a 1.x renderer left under `.claude/agents/` is stale, and so is a steward-guard registration (B11).
 */
const BOOTSTRAP_HASH = 'b4df6f906cd3d27a26061eddc3cf997f58015866fc610a195c5b228d619ef2eb';
const skillPaths = ['.agents/skills/ia-authoring/SKILL.md', '.claude/skills/ia-authoring/SKILL.md'];
/** B9: the markers the 1.x renderers wrote here and in consumer workspaces, owned beside the packet's marker. */
const LEGACY_MARKERS: readonly string[] = [
  '<!-- Generated by tools/projections/generate.ts; edit the cited native records. -->',
  '<!-- Generated by ia host; edit the cited native records. -->',
];
/** The settings file whose steward-guard group a registration owns, and that registration's ownership state (B11). */
export const GUARD_SETTINGS = '.claude/settings.local.json';
const GUARD_STATE = `.ia/distributions/hosts/claude-guard-${HOST_REGISTRATION}.json`;
/** Design row 27: every refusal names the one command to run next; regeneration is this one. */
const GENERATE = 'run "pnpm projections:generate"';
/** The native corpus findings an admission refusal stands on are what `pnpm native:check` prints. */
const SHOW_FINDINGS = 'run "pnpm native:check" for the findings';
/**
 * Admission has passed when the output set is checked, so a path outside it is the renderer's: its contract is pinned
 * by this directory's tests, which render this repository through `publishArtifacts`.
 */
const SHOW_RENDERER = 'run "pnpm exec vitest run --config vitest.tools.config.mts tools/projections" for the renderer';
function safe(root: string, path: string): string {
  const base = resolve(root),
    target = resolve(base, path),
    rel = relative(base, target);
  if (isAbsolute(rel) || rel === '..' || rel.startsWith('..' + sep))
    throw new Error(`Projection path escapes root: ${path}; ${SHOW_RENDERER} that emitted it`);
  // Another case or normalization of the same names is not an alias (#315); a link anywhere in the root still is.
  if (!unaliased(base, realpathSync.native(base)))
    throw new Error(
      `Projection root is aliased; open the repository at ${realpathSync.native(base)}, then ${GENERATE}`,
    );
  let current = base;
  for (const part of ['', ...rel.split(sep)]) {
    current = resolve(current, part);
    try {
      if (lstatSync(current).isSymbolicLink())
        throw new Error(
          `Projection path is aliased: ${path}; replace the link at ${relative(base, current)}, then ${GENERATE}`,
        );
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
  }
  return target;
}
/** A file this generator owns: it carries the packet's marker or a legacy one, or it is the bootstrap skill. */
function owned(bytes: Buffer, path: string): boolean {
  const lines = bytes.toString('utf8').split(/\r?\n/);
  return (
    [PACKET_MARKER, ...LEGACY_MARKERS].some((marker) => lines.includes(marker)) ||
    (skillPaths.includes(path) && createHash('sha256').update(bytes).digest('hex') === BOOTSTRAP_HASH)
  );
}
/** Only an exact known repository steward at its original path is safe to delete. */
function staleSteward(bytes: Buffer, path: string): boolean {
  return LEGACY_STEWARDS[path]?.includes(createHash('sha256').update(bytes).digest('hex')) ?? false;
}
/**
 * B11: the removal of a steward-guard registration this checkout owns, or null when it owns none. This repository has
 * no `.ia/release.json`, so `ia host` refuses here and only a hand-made or 1.x registration can exist; it is retired
 * through apps/distribution's guard registration, as `applyHostProjection` retires a consumer's.
 */
function retirement(root: string): GuardPlan | null {
  if (!existsSync(safe(root, GUARD_STATE))) return null;
  try {
    return planGuardRegistration(root, { remove: HOST_REGISTRATION });
  } catch (error) {
    throw new Error(
      `The steward guard registration cannot be retired: ${error instanceof Error ? error.message : String(error)}; delete ${GUARD_STATE} and the IA guard group in ${GUARD_SETTINGS}, then ${GENERATE}`,
    );
  }
}
/**
 * I/O seam used by the real composition root and bounded filesystem tests. Returns what drifted (`write` false) or
 * changed (`write` true): `GUARD_SETTINGS` when a steward-guard registration is retired, each stale steward file under
 * `.claude/agents/`, then each file whose bytes differ. Everything is checked before anything changes: the output set,
 * every managed path, the stale steward files and the guard's removal. `--write` then retires the guard first (B11),
 * deletes the stale steward files and publishes the files.
 */
export function publishArtifacts(root: string, artifacts: readonly HostFile[], write: boolean): readonly string[] {
  const pending: HostFile[] = [];
  if (
    new Set(artifacts.map((a) => a.path)).size !== artifacts.length ||
    artifacts.some((a) => a.path !== 'CLAUDE.md' && !skillPaths.includes(a.path))
  )
    throw new Error(`Invalid projection output set; ${SHOW_RENDERER} that emitted it`);
  // No steward file is rendered. Only a proven M4 file is stale; a marker alone is no deletion authority.
  const stale: string[] = [],
    agents = safe(root, '.claude/agents');
  if (existsSync(agents))
    for (const entry of readdirSync(agents, { withFileTypes: true })) {
      const path = `.claude/agents/${entry.name}`;
      if (entry.isFile() && staleSteward(readFileSync(safe(root, path)), path)) stale.push(path);
    }
  stale.sort();
  // Preflight the complete set before publishing any file.
  for (const artifact of artifacts) {
    const target = safe(root, artifact.path);
    if (existsSync(target)) {
      const bytes = readFileSync(target);
      if (bytes.equals(Buffer.from(artifact.text))) continue;
      if (!owned(bytes, artifact.path))
        throw new Error(`Refusing unmanaged projection: ${artifact.path}; delete ${artifact.path}, then ${GENERATE}`);
    }
    pending.push(artifact);
  }
  const guard = retirement(root);
  if (write) {
    if (guard !== null) applyGuardRegistration(guard);
    for (const path of stale) {
      const target = safe(root, path);
      if (existsSync(target) && !staleSteward(readFileSync(target), path))
        throw new Error(`Projection changed before publication: ${path}; ${GENERATE} again`);
      if (existsSync(target)) unlinkSync(target);
    }
    for (const artifact of pending) {
      const target = safe(root, artifact.path);
      mkdirSync(dirname(target), { recursive: true });
      const temp = `${target}.${randomUUID()}.tmp`;
      try {
        safe(root, relative(resolve(root), temp));
        writeFileSync(temp, artifact.text, { encoding: 'utf8', flag: 'wx' });
        safe(root, artifact.path);
        if (existsSync(target) && !owned(readFileSync(target), artifact.path))
          throw new Error(`Projection changed before publication: ${artifact.path}; ${GENERATE} again`);
        renameSync(temp, target);
      } finally {
        safe(root, relative(resolve(root), temp));
        if (existsSync(temp)) unlinkSync(temp);
      }
    }
  }
  return [...(guard === null ? [] : [GUARD_SETTINGS]), ...stale, ...pending.map((a) => a.path)];
}
/** The repository-target files the claude adapter renders from this repository's own admitted records. */
export function renderProjections(root: string): readonly HostFile[] {
  const db = open(root, { cache: false });
  try {
    if (db.report.findings.some((f) => f.severity === 'error'))
      throw new Error(`Native corpus has errors; projections refused; ${SHOW_FINDINGS}`);
    const { packet, digest, hostNote } = renderPacket(db, db.resolveScope().token, packetCatalog());
    return renderHost('claude', packet, digest, hostNote, 'repository').files;
  } finally {
    db.close();
  }
}
export const generateProjections = (root: string, write: boolean): readonly string[] =>
  publishArtifacts(root, renderProjections(root), write);
if (isEntry(process.argv[1], import.meta.url)) {
  try {
    if (process.argv.length !== 3 || !['--check', '--write'].includes(process.argv[2]!))
      throw new Error(`Usage: generate.ts --check|--write; ${GENERATE}`);
    const write = process.argv[2] === '--write',
      changed = generateProjections(resolve(import.meta.dirname, '../..'), write);
    if (write && changed.includes(GUARD_SETTINGS)) process.stdout.write('guard retired\n');
    process.stdout.write(
      `${write ? 'Updated' : 'Drifted'} projections: ${changed.length}${changed.length ? '\n' + changed.join('\n') : ''}\n`,
    );
    if (!write && changed.length) {
      // Design row 27: a failed check names the one command that brings the files back in line.
      process.stdout.write(`To update them, ${GENERATE}.\n`);
      process.exitCode = 1;
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    // Every refusal raised here names its next command; one raised beneath the generator (the db open, the file system)
    // names none, so it gains the regeneration that follows its repair.
    const named = [GENERATE, SHOW_FINDINGS, SHOW_RENDERER].some((next) => message.includes(next));
    process.stderr.write(`${message}${named ? '' : `; once that is repaired, ${GENERATE}`}\n`);
    process.exitCode = 1;
  }
}
