import { spawnSync } from 'node:child_process';
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { PACKET_MARKER } from '../../packages/runtime/src/packet-host.js';
import { guardGroup } from '../../apps/distribution/src/guard-registration.js';
import { json } from '../../apps/distribution/src/files.js';
import { editJson, presentJson } from '../../apps/distribution/src/json-edit.js';
import { GUARD_SETTINGS, generateProjections, publishArtifacts, renderProjections } from './generate.js';

// Milestone position-packet task replace-renderers: this repository's committed projection is the position packet,
// rendered by the claude adapter for the repository target; a 1.x steward file or steward-guard registration is stale.
const root = resolve(import.meta.dirname, '../..'),
  temporary: string[] = [];
const FILES = ['CLAUDE.md', '.claude/skills/ia-authoring/SKILL.md', '.agents/skills/ia-authoring/SKILL.md'];
/** The two markers the 1.x renderers wrote (B9): this repository's and `ia host`'s. */
const REPO_MARK = '<!-- Generated by tools/projections/generate.ts; edit the cited native records. -->',
  HOST_MARK = '<!-- Generated by ia host; edit the cited native records. -->';
const GUARD_STATE = '.ia/distributions/hosts/claude-guard-workspace.json';
function temp(): string {
  const path = mkdtempSync(resolve(tmpdir(), 'ia-projection-tests-'));
  temporary.push(path);
  return path;
}
afterEach(() => {
  for (const path of temporary.splice(0)) {
    const rel = relative(tmpdir(), path);
    if (isAbsolute(rel) || !rel.startsWith('ia-projection-tests-') || rel.includes('..'))
      throw new Error('Unsafe cleanup');
    rmSync(path, { recursive: true, force: true });
  }
  // A copied native corpus is hundreds of files, slow to delete on a loaded machine.
}, 60_000);
const put = (base: string, path: string, text: string): void => {
  mkdirSync(dirname(resolve(base, path)), { recursive: true });
  writeFileSync(resolve(base, path), text);
};
const read = (base: string, path: string): string => readFileSync(resolve(base, path), 'utf8');
/** A copy of this repository's native corpus, the layout the generator reads, with no projection file yet. */
function copy(): string {
  const base = temp();
  cpSync(resolve(root, '.ia/src'), resolve(base, '.ia/src'), { recursive: true });
  return base;
}
/**
 * A steward-guard registration as a 1.x `ia host` wrote it over an existing `settings` file: the group
 * guard-registration derives for this root appended to its PreToolUse array in place, and the ownership state its
 * planner records, the containers that were already there kept as `existing`. A removal never reads the cache.
 */
function registerGuard(base: string, settings: string): string {
  const real = realpathSync(base),
    cache = temp(),
    group = guardGroup(join(cache, 'scripts/ia.mjs'), real),
    existing = presentJson(settings, [['hooks'], ['hooks', 'PreToolUse']]);
  const text = editJson(settings, ['hooks', 'PreToolUse', -1], group, existing);
  put(base, GUARD_SETTINGS, text);
  put(
    base,
    GUARD_STATE,
    json({
      format: 'ia.guard-registration-state.v1',
      id: 'workspace',
      cache,
      release: 'a'.repeat(64),
      created: false,
      group,
      ...(existing.length === 0 ? {} : { existing }),
    }),
  );
  return text;
}
/** A token GitHub would render as a mention: a bare `@<word>` outside every code span. */
const bare = (text: string): readonly string[] =>
  text.replace(/(`+)[\s\S]*?(?<!`)\1(?!`)/g, '').match(/(?<![\w.\-/@`])@[a-z][a-z0-9-]*(?![\w\-/@])/g) ?? [];

it('renders this repository as its position packet: CLAUDE.md and both skills, no steward agent, as committed', () => {
  const files = renderProjections(root);
  expect(files.map((file) => file.path)).toEqual(FILES);
  for (const file of files) {
    expect(file.text.split('\n'), file.path).toContain(PACKET_MARKER);
    expect(file.text, file.path).toBe(read(root, file.path));
  }
  const claude = files[0]!.text;
  expect(claude.startsWith(`${PACKET_MARKER}\n\n# IA position packet: language-workspace\n`)).toBe(true);
  // One participant entry (plan task self-host-participant-records), and no host note in a committed file.
  const participants = claude.split('## Participants\n\n')[1]!.split('\n\n')[0]!.split('\n');
  expect(participants).toEqual([
    '- `agent-system/binding/agent/language-participant`: The IDE agent operating in the language workspace, any vendor.',
  ]);
  expect(claude).not.toContain('Host note');
  // GitHub renders the committed file: every IA word in it is a code span, never a mention.
  expect(claude).toContain('`@workspace`');
  expect(bare(claude)).toEqual([]);
  // The tree holds no marked steward agent and no guard registration: the check finds nothing to do.
  expect(generateProjections(root, false)).toEqual([]);
  const base = temp();
  expect(publishArtifacts(base, files, false)).toEqual(FILES);
  publishArtifacts(base, files, true);
  expect(publishArtifacts(base, files, false)).toEqual([]);
});
it('checks without writing, publishes changed bytes and leaves equal bytes untouched', () => {
  const base = temp(),
    artifact = { path: 'CLAUDE.md', text: PACKET_MARKER + '\nfirst\n' };
  expect(publishArtifacts(base, [artifact], false)).toEqual(['CLAUDE.md']);
  expect(publishArtifacts(base, [artifact], true)).toEqual(['CLAUDE.md']);
  const time = statSync(resolve(base, 'CLAUDE.md')).mtimeMs;
  expect(publishArtifacts(base, [artifact], true)).toEqual([]);
  expect(statSync(resolve(base, 'CLAUDE.md')).mtimeMs).toBe(time);
  const changed = { ...artifact, text: PACKET_MARKER + '\nsecond\n' };
  expect(publishArtifacts(base, [changed], true)).toEqual(['CLAUDE.md']);
  expect(read(base, 'CLAUDE.md')).toBe(changed.text);
  // A file a 1.x renderer marked is owned, so it is replaced rather than refused.
  put(base, 'CLAUDE.md', `${REPO_MARK}\n\n# IA language\n`);
  expect(publishArtifacts(base, [changed], true)).toEqual(['CLAUDE.md']);
  expect(read(base, 'CLAUDE.md')).toBe(changed.text);
});
it('preflights unmanaged files before writing and refuses arbitrary outputs, steward agents and aliases', () => {
  const base = temp(),
    outside = temp();
  writeFileSync(resolve(base, 'CLAUDE.md'), 'User-authored');
  const first = { path: '.claude/skills/ia-authoring/SKILL.md', text: PACKET_MARKER },
    last = { path: 'CLAUDE.md', text: PACKET_MARKER };
  // Design row 27: the refusal names the file to delete and the one command that follows.
  expect(() => publishArtifacts(base, [first, last], true)).toThrow(
    'Refusing unmanaged projection: CLAUDE.md; delete CLAUDE.md, then run "pnpm projections:generate"',
  );
  expect(() => statSync(resolve(base, first.path))).toThrow();
  for (const path of ['../escape', '.claude/agents/fresh.md', '.claude/skills/ia-authoring/parts/orient.md'])
    expect(() => publishArtifacts(base, [{ path, text: PACKET_MARKER }], true), path).toThrow('output set');
  symlinkSync(outside, resolve(base, '.agents'), 'junction');
  expect(() =>
    publishArtifacts(base, [{ path: '.agents/skills/ia-authoring/SKILL.md', text: PACKET_MARKER }], true),
  ).toThrow('aliased');
});
it('reports a marked steward file as stale in a check, deletes it on write and leaves an unmarked one', () => {
  const base = temp(),
    files = [{ path: 'CLAUDE.md', text: `${PACKET_MARKER}\n` }];
  for (const [name, marker] of [
    ['repo-steward.md', REPO_MARK],
    ['host-steward.md', HOST_MARK],
  ] as const)
    put(base, `.claude/agents/${name}`, `---\nname: ${name}\n---\n\n${marker}\n`);
  put(base, '.claude/agents/mine.md', 'my own agent\n');
  expect(publishArtifacts(base, files, false)).toEqual([
    '.claude/agents/host-steward.md',
    '.claude/agents/repo-steward.md',
    'CLAUDE.md',
  ]);
  expect(existsSync(resolve(base, '.claude/agents/repo-steward.md'))).toBe(true);
  expect(publishArtifacts(base, files, true)).toHaveLength(3);
  for (const name of ['repo-steward.md', 'host-steward.md'])
    expect(existsSync(resolve(base, `.claude/agents/${name}`)), name).toBe(false);
  expect(read(base, '.claude/agents/mine.md')).toBe('my own agent\n');
  expect(publishArtifacts(base, files, false)).toEqual([]);
});
it('upgrades a copy of this repository: retires an owned guard group before deleting a 1.x steward file (B11)', () => {
  const base = copy(),
    agent = '.claude/agents/public-governance-system-steward.md',
    legacy = `---\nname: public-governance-system-steward\n---\n\n${REPO_MARK}\n\nSource revision: x\n`,
    permissions =
      '{\n  "permissions": {\n    "allow": [\n      "Read"\n    ]\n  },\n  "hooks": {\n    "PreToolUse": []\n  }\n}\n';
  put(base, agent, legacy);
  const settings = registerGuard(base, permissions);
  // The check reports both, and writes nothing.
  expect(generateProjections(base, false)).toEqual([GUARD_SETTINGS, agent, ...FILES]);
  expect(read(base, GUARD_SETTINGS)).toBe(settings);
  expect(read(base, agent)).toBe(legacy);
  // The write retires the guard through apps/distribution's guard registration, deletes the steward file and
  // renders the packet; the settings file is byte for byte what it was before the registration, every other key and
  // the containers that were already there kept.
  expect(settings).not.toBe(permissions);
  expect(generateProjections(base, true)).toEqual([GUARD_SETTINGS, agent, ...FILES]);
  expect(existsSync(resolve(base, GUARD_STATE))).toBe(false);
  expect(existsSync(resolve(base, agent))).toBe(false);
  expect(read(base, GUARD_SETTINGS)).toBe(permissions);
  for (const path of FILES) expect(read(base, path).split('\n'), path).toContain(PACKET_MARKER);
  expect(generateProjections(base, false)).toEqual([]);
  // Copying the native corpus (hundreds of files) and deleting it again dominate this test: allow for a loaded machine.
}, 180_000);
it('refuses a guard registration it cannot retire, naming the repair, before changing anything', () => {
  const base = temp(),
    agent = '.claude/agents/stale.md';
  put(base, agent, `${REPO_MARK}\n`);
  registerGuard(base, '{\n  "hooks": {\n    "PreToolUse": []\n  }\n}\n');
  // The group changed by hand: the retirement refuses it, so the check and the write both stop.
  const changed = JSON.parse(read(base, GUARD_SETTINGS));
  changed.hooks.PreToolUse[0].timeout = 99;
  put(base, GUARD_SETTINGS, JSON.stringify(changed, null, 2) + '\n');
  for (const write of [false, true])
    expect(() => publishArtifacts(base, [{ path: 'CLAUDE.md', text: PACKET_MARKER }], write)).toThrow(
      `; delete ${GUARD_STATE} and the IA guard group in ${GUARD_SETTINGS}, then run "pnpm projections:generate"`,
    );
  expect(existsSync(resolve(base, agent))).toBe(true);
  expect(existsSync(resolve(base, GUARD_STATE))).toBe(true);
  expect(existsSync(resolve(base, 'CLAUDE.md'))).toBe(false);
});
it('refuses generating a partial corpus with admission errors, naming the command that prints them', () => {
  expect(() => generateProjections(resolve(root, 'packages/compliance/fixtures/loop'), false)).toThrow(
    'Native corpus has errors; projections refused; run "pnpm native:check" for the findings',
  );
});

it('names one next command in every refusal the generator raises (design row 27)', () => {
  // Every construction site in the source, so a refusal added later without a next command fails here.
  const source = readFileSync(resolve(import.meta.dirname, 'generate.ts'), 'utf8');
  const messages = [...source.matchAll(/throw new Error\(\s*`([^`]*)`/g)].map((match) => match[1]!);
  expect(source.match(/throw new Error\(/g)).toHaveLength(messages.length);
  expect(messages).toHaveLength(10);
  for (const message of messages)
    expect(message.match(/\$\{(?:GENERATE|SHOW_FINDINGS|SHOW_RENDERER)\}/g), message).toHaveLength(1);
});
it('names the next command for a usage refusal of the generator run as a program', () => {
  const result = spawnSync(
    process.execPath,
    ['--conditions=development', '--import', 'tsx', resolve(import.meta.dirname, 'generate.ts')],
    { cwd: root, encoding: 'utf8', timeout: 15000 },
  );
  expect(result.status, result.stderr).toBe(1);
  expect(result.stdout).toBe('');
  expect(result.stderr.split(/\r?\n/)).toContain('Usage: generate.ts --check|--write; run "pnpm projections:generate"');
});
