/**
 * Operator decision 2026-09-23 ("narrow + disclose"): a workspace with a projection ownership state is a consumer
 * workspace, where the guard protects only what `ia host` owns plus the native installation state. Steward
 * enforcement on `.ia/src/systems/<name>/**` is the same in both modes. tests/hook.test.ts keeps the legacy list.
 */
import {
  cpSync,
  fstatSync,
  linkSync,
  readFileSync,
  renameSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { isAbsolute, relative, resolve } from 'node:path';
import { afterEach, expect, it, vi } from 'vitest';
import { evaluateHook } from '../src/main.js';

const fileSeam = vi.hoisted(() => ({
  afterOpen: undefined as ((path: unknown, fd: number) => void) | undefined,
  beforeRead: undefined as ((fd: number, length: number) => void) | undefined,
}));
vi.mock('node:fs', async (importOriginal) => {
  const actual = await importOriginal<typeof import('node:fs')>();
  return {
    ...actual,
    openSync: (...args: Parameters<typeof actual.openSync>) => {
      const fd = actual.openSync(...args);
      fileSeam.afterOpen?.(args[0], fd);
      return fd;
    },
    readSync: (fd: number, buffer: Buffer, offset: number, length: number, position: number | null) => {
      fileSeam.beforeRead?.(fd, length);
      return actual.readSync(fd, buffer, offset, length, position);
    },
  };
});

// Steward cases open the disk-backed native fixture.
vi.setConfig({ testTimeout: 30_000 });

const fixture = resolve(import.meta.dirname, '../../../packages/compliance/fixtures/loop');
const roots: string[] = [];
const hash = 'a'.repeat(64),
  other = 'b'.repeat(64);
function workspace(copy = false): string {
  const root = mkdtempSync(resolve(tmpdir(), 'ia-consumer-guard-'));
  roots.push(root);
  if (copy) cpSync(fixture, root, { recursive: true });
  mkdirSync(resolve(root, '.ia/distributions/hosts'), { recursive: true });
  return root;
}
function write(root: string, name: string, value: unknown): void {
  writeFileSync(
    resolve(root, '.ia/distributions/hosts', name),
    typeof value === 'string' ? value : JSON.stringify(value),
  );
}
function projection(host: 'claude' | 'codex', files: Record<string, unknown>) {
  return { format: 'ia.host-projection-state.v1', host, files };
}
function check(root: string, path: string, extra: Record<string, unknown> = {}) {
  return evaluateHook(root, {
    hook_event_name: 'PreToolUse',
    tool_name: 'Write',
    tool_input: { file_path: resolve(root, path), content: 'x' },
    ...extra,
  });
}
function code(root: string, path: string, extra: Record<string, unknown> = {}): string | undefined {
  return check(root, path, extra).hookSpecificOutput?.permissionDecisionReason.split(':')[0];
}
afterEach(() => {
  fileSeam.afterOpen = undefined;
  fileSeam.beforeRead = undefined;
  for (const root of roots.splice(0)) {
    const path = relative(tmpdir(), root);
    if (isAbsolute(path) || !path.startsWith('ia-consumer-guard-') || path.includes('..'))
      throw new Error('Unsafe cleanup');
    rmSync(root, { recursive: true, force: true });
  }
});

it("leaves the user's own instruction, skill and agent files editable and protects only the owned projection files", () => {
  const root = workspace();
  write(
    root,
    'claude-projection.json',
    projection('claude', { '.claude/agents/demo-steward.md': hash, '.claude/rules/ia-workspace.md': hash }),
  );
  for (const path of [
    'CLAUDE.md',
    'AGENTS.md',
    '.claude/skills/my-own/SKILL.md',
    '.claude/skills/ia-authoring/SKILL.md',
    '.agents/skills/ia-authoring/SKILL.md',
    '.claude/agents/my-reviewer.md',
    '.codex/agents/owner.toml',
    '.codex/config.toml',
    'docs/ordinary.md',
  ])
    expect(check(root, path), path).toEqual({});
  for (const path of [
    '.claude/rules/ia-workspace.md',
    // A 1.x steward file stays protected while the state lists it, until the next projection apply removes it (B9).
    '.claude/agents/demo-steward.md',
    '.ia/distributions.lock.json',
    '.ia/distributions/active.json',
    '.ia/distributions/hosts/claude-projection.json',
    // The receipt the projection apply writes beside its state (B12).
    '.ia/distributions/hosts/claude-receipt.json',
  ])
    expect(code(root, path, { agent_type: 'demo-steward' }), path).toBe('IA-HOOK-PROJECTION-MANAGED');
  // In a consumer workspace the state decides, so a marked steward file it does not list is the user's.
  mkdirSync(resolve(root, '.claude/agents'), { recursive: true });
  writeFileSync(
    resolve(root, '.claude/agents/stray-steward.md'),
    '---\nname: stray-steward\n---\n\n<!-- Generated by ia host; edit the cited native records. -->\n',
  );
  expect(check(root, '.claude/agents/stray-steward.md')).toEqual({});
  if (process.platform === 'win32') {
    expect(code(root, '.CLAUDE/Rules/IA-Workspace.MD')).toBe('IA-HOOK-PROJECTION-MANAGED');
    expect(check(root, 'Claude.MD')).toEqual({});
  }
});

it('keeps settings.local.json protected while a guard marker exists and .codex/config.toml while the Codex registration exists', () => {
  const root = workspace();
  write(root, 'claude-projection.json', projection('claude', { '.claude/rules/ia-workspace.md': hash }));
  expect(check(root, '.claude/settings.local.json')).toEqual({});
  write(root, 'claude-guard-workspace.json', {
    format: 'ia.guard-registration-state.v1',
    id: 'workspace',
    cache: root,
    release: hash,
    created: true,
    group: { matcher: 'Write|Edit|MultiEdit', hooks: [] },
  });
  expect(code(root, '.claude/settings.local.json')).toBe('IA-HOOK-PROJECTION-MANAGED');
  write(root, 'codex-workspace.json', '{}\n');
  expect(code(root, '.codex/config.toml')).toBe('IA-HOOK-PROJECTION-MANAGED');
});

it("reads either host's projection state, including an interrupted apply's two accepted hashes", () => {
  const root = workspace();
  write(root, 'codex-projection.json', projection('codex', { 'AGENTS.md': [hash, other] }));
  expect(code(root, 'AGENTS.md')).toBe('IA-HOOK-PROJECTION-MANAGED');
  expect(check(root, 'CLAUDE.md')).toEqual({});
  expect(check(root, '.agents/skills/ia-authoring/SKILL.md')).toEqual({});
  expect(check(root, '.claude/rules/ia-workspace.md')).toEqual({});
});

it("still refuses records under .ia/src/systems/<name>/ from anyone but that system's steward", () => {
  const root = workspace(true);
  write(root, 'claude-projection.json', projection('claude', { '.claude/rules/ia-workspace.md': hash }));
  const record = '.ia/src/systems/governance-system/records/x.ia';
  expect(code(root, record)).toBe('IA-HOOK-IDENTITY-UNAVAILABLE');
  expect(code(root, record, { agent_type: 'agent-steward' })).toBe('IA-HOOK-NOT-STEWARD');
  expect(check(root, record, { agent_type: 'governance-steward' })).toEqual({});
});

it.each([
  ['unparseable bytes', 'garbage'],
  ['another format', { ...projection('claude', {}), format: 'ia.host-projection-state.v2' }],
  ['a host mismatch', projection('codex', {})],
  ['an extra member', { ...projection('claude', {}), extra: true }],
  ['a path outside the allowlist', projection('claude', { '.ia/src/systems/demo/x.ia': hash })],
  ['a malformed hash', projection('claude', { '.claude/rules/ia-workspace.md': 'nothex' })],
  ['three accepted hashes', projection('claude', { '.claude/rules/ia-workspace.md': [hash, other, 'c'.repeat(64)] })],
])('fails closed on a projection state with %s', (_label, value) => {
  const root = workspace();
  write(root, 'claude-projection.json', value);
  for (const path of ['CLAUDE.md', '.claude/rules/ia-workspace.md', '.claude/skills/my-own/SKILL.md'])
    expect(code(root, path), path).toBe('IA-HOOK-PATH-UNSAFE');
  // A path no projection rule could reach does not depend on the state.
  expect(check(root, 'docs/ordinary.md')).toEqual({});
});

it('fails closed when the projection state is not a plain file', () => {
  const root = workspace();
  mkdirSync(resolve(root, '.ia/distributions/hosts/claude-projection.json'));
  expect(code(root, 'CLAUDE.md')).toBe('IA-HOOK-PATH-UNSAFE');
});

it('protects both settings layers and the exact external launcher of an owned guard only', () => {
  const root = workspace(),
    cache = workspace();
  const marker = {
    format: 'ia.guard-registration-state.v1',
    id: 'workspace',
    cache,
    release: hash,
    created: true,
    group: { matcher: 'Write|Edit|MultiEdit', hooks: [] },
  };
  const launcher = resolve(cache, 'scripts/ia.mjs');
  for (const path of ['.claude/settings.json', '.claude/settings.local.json', launcher])
    expect(check(root, path), path).toEqual({});
  write(root, 'claude-guard-workspace.json', marker);
  for (const path of ['.claude/settings.json', '.claude/settings.local.json', launcher])
    expect(code(root, path, { agent_type: 'work-steward' }), path).toBe('IA-HOOK-PROJECTION-MANAGED');
  for (const path of [
    '.claude/ordinary.json',
    '.claude/hooks/unowned.mjs',
    resolve(cache, 'scripts/unowned.mjs'),
    '.ia/src/floor/taxonomy.system.ia',
    'apps/steward-hook/src/main.ts',
  ])
    expect(check(root, path), path).toEqual({});
  const pending = workspace();
  write(pending, 'guard-pending.json', {
    format: 'ia.guard-registration-pending.v1',
    id: 'workspace',
    before: { config: '{}', state: JSON.stringify(marker) },
    after: { config: null, state: null },
  });
  expect(code(pending, launcher)).toBe('IA-HOOK-PROJECTION-MANAGED');
  expect(code(pending, '.claude/settings.json')).toBe('IA-HOOK-PROJECTION-MANAGED');
});

it('recognizes the fixed source registration without claiming unrelated user hooks or settings', () => {
  const root = workspace();
  mkdirSync(resolve(root, '.claude/hooks'), { recursive: true });
  writeFileSync(resolve(root, '.claude/hooks/steward-write.mjs'), '// Synthetic fixed-path launcher fixture.\n');
  const registered = {
    hooks: {
      PreToolUse: [
        {
          matcher: 'Write|Edit|MultiEdit',
          hooks: [
            {
              type: 'command',
              command: 'node',
              args: [`\${CLAUDE_PROJECT_DIR}/.claude/hooks/steward-write.mjs`, '--root', `\${CLAUDE_PROJECT_DIR}`],
            },
          ],
        },
      ],
    },
    permissions: { allow: [] },
  };
  const paths = ['.claude/settings.json', '.claude/settings.local.json', '.claude/hooks/steward-write.mjs'];
  writeFileSync(
    resolve(root, '.claude/settings.json'),
    JSON.stringify({
      hooks: { PreToolUse: [{ matcher: 'Write', hooks: [{ type: 'command', command: 'my-own-hook' }] }] },
    }),
  );
  for (const path of paths) expect(check(root, path), path).toEqual({});
  writeFileSync(resolve(root, '.claude/settings.json'), JSON.stringify(registered));
  for (const tool of ['Write', 'Edit', 'MultiEdit'])
    for (const path of paths) {
      const event = {
        hook_event_name: 'PreToolUse',
        tool_name: tool,
        tool_input: { file_path: resolve(root, path), edits: [] },
        agent_type: 'hook-authoring-steward',
      };
      expect(evaluateHook(root, event).hookSpecificOutput?.permissionDecisionReason, tool + ':' + path).toContain(
        'IA-HOOK-PROJECTION-MANAGED',
      );
      expect(evaluateHook(root, event).hookSpecificOutput?.permissionDecisionReason).toContain('trusted operator edit');
    }
  expect(check(root, '.claude/hooks/my-own-hook.mjs')).toEqual({});
  writeFileSync(
    resolve(root, '.claude/settings.json'),
    JSON.stringify({
      ...registered,
      hooks: {
        PreToolUse: [
          {
            ...registered.hooks.PreToolUse[0],
            hooks: [{ ...registered.hooks.PreToolUse[0]!.hooks[0], args: ['another-launcher.mjs', '--root', root] }],
          },
        ],
      },
    }),
  );
  for (const path of paths) expect(check(root, path), path).toEqual({});
});

it('refuses aliases to the owned cached launcher without extending ownership to its other code', () => {
  const root = workspace(),
    cache = workspace();
  mkdirSync(resolve(cache, 'scripts'));
  writeFileSync(resolve(cache, 'scripts/ia.mjs'), '// Fixture launcher.\n');
  write(root, 'claude-guard-workspace.json', {
    format: 'ia.guard-registration-state.v1',
    id: 'workspace',
    cache,
    release: hash,
    created: true,
    group: { matcher: 'Write|Edit|MultiEdit', hooks: [] },
  });
  symlinkSync(cache, resolve(root, 'cache-alias'), process.platform === 'win32' ? 'junction' : 'dir');
  expect(code(root, 'cache-alias/scripts/ia.mjs')).toBe('IA-HOOK-PATH-UNSAFE');
  expect(check(root, resolve(cache, 'code/guard.js'))).toEqual({});
  write(root, 'claude-guard-workspace.json', { format: 'malformed' });
  expect(code(root, '.claude/settings.json')).toBe('IA-HOOK-PATH-UNSAFE');
});

it.each(['replacement', 'growth', 'hardlink-write'])(
  'fails closed if a legacy steward changes by %s during its bounded handle read',
  (kind) => {
    const root = workspace(),
      path = '.claude/agents/old-steward.md',
      target = resolve(root, path);
    mkdirSync(resolve(root, '.claude/agents'), { recursive: true });
    const marker = '<!-- Generated by ia host; edit the cited native records. -->\n';
    writeFileSync(target, marker);
    if (kind === 'hardlink-write') linkSync(target, `${target}.alias`);
    let opened: number | undefined,
      requested = 0,
      changed = false;
    fileSeam.afterOpen = (name, fd) => {
      if (name !== target || opened !== undefined) return;
      opened = fd;
      if (kind === 'replacement') {
        renameSync(target, `${target}.before`);
        writeFileSync(target, 'foreign replacement');
      }
    };
    fileSeam.beforeRead = (fd, length) => {
      if (fd !== opened) return;
      requested += length;
      if (changed) return;
      changed = true;
      writeFileSync(
        kind === 'hardlink-write' ? `${target}.alias` : target,
        kind === 'growth' ? marker + 'x'.repeat(2 * 1024 * 1024) : 'changed through the alias',
      );
    };
    expect(code(root, path)).toBe('IA-HOOK-PATH-UNSAFE');
    expect(opened).toBeTypeOf('number');
    expect(() => fstatSync(opened!)).toThrow();
    if (kind === 'replacement') {
      expect(requested).toBe(0);
      expect(readFileSync(`${target}.before`, 'utf8')).toBe(marker);
    } else {
      expect(changed).toBe(true);
      expect(requested).toBeLessThanOrEqual(2 * (1024 * 1024 + 1));
    }
  },
);

it('preserves legacy marker decisions for stable files, including hardlinks and oversized personal files', () => {
  const root = workspace(),
    path = '.claude/agents/old-steward.md',
    target = resolve(root, path);
  mkdirSync(resolve(root, '.claude/agents'), { recursive: true });
  expect(check(root, path)).toEqual({});
  writeFileSync(target, 'personal agent');
  expect(check(root, path)).toEqual({});
  writeFileSync(target, '<!-- Generated by ia host; edit the cited native records. -->\n');
  linkSync(target, `${target}.alias`);
  expect(code(root, path)).toBe('IA-HOOK-PROJECTION-MANAGED');
  writeFileSync(target, 'x'.repeat(1024 * 1024 + 1));
  expect(check(root, path)).toEqual({});
});
