import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { expect, it } from 'vitest';
import { digest } from '@inventarch/graph';
import { PACKET_MARKER, entryCount, renderHost, renderPacket } from '../src/index.js';
import type {
  HostOutput,
  PacketCatalogRow,
  PacketHost,
  PacketHostNote,
  PacketOutput,
  PacketTarget,
  PositionPacket,
} from '../src/index.js';
import { database, freshInit } from './workspace.js';

// R20 (position-and-projection §4, the host adapter contract, and items 11, 12 and 14; plan amendments B9, B10 and
// B12): the claude and codex adapters render one position packet as files with the generated marker, and a receipt.
const repository = resolve(import.meta.dirname, '../../..'),
  version = (JSON.parse(readFileSync(resolve(import.meta.dirname, '../package.json'), 'utf8')) as { version: string })
    .version,
  HOSTS: readonly PacketHost[] = ['claude', 'codex'],
  TARGETS: readonly PacketTarget[] = ['repository', 'consumer'],
  LEGACY = '<!-- Generated by tools/projections/generate.ts; edit the cited native records. -->',
  participant = 'agent-system/binding/agent/acme';
const PATHS: Readonly<Record<PacketHost, Readonly<Record<PacketTarget, readonly string[]>>>> = {
  claude: {
    repository: ['CLAUDE.md', '.claude/skills/ia-authoring/SKILL.md', '.agents/skills/ia-authoring/SKILL.md'],
    consumer: ['.claude/rules/ia-workspace.md', '.claude/skills/ia-authoring/SKILL.md'],
  },
  codex: {
    repository: ['AGENTS.md', '.agents/skills/ia-authoring/SKILL.md'],
    consumer: ['AGENTS.md', '.agents/skills/ia-authoring/SKILL.md'],
  },
};
/** A catalog fixture: the runtime takes the catalog as data (B2), and the CLI pins its own rows. */
const CATALOG: readonly PacketCatalogRow[] = [
  { command: 'ia position', mode: 'read', move: 'Observation', refuses: 'an unadmitted seat', next: 'ia position' },
  { command: 'ia next', mode: 'read', move: 'Observation', refuses: 'several plans', next: 'ia next --seat <plan>' },
];
/** The consumer skill as compliance's retired renderWorkspaceProjection wrote it, its marker line aside (B10). */
const consumerSkill = (revision: string): string =>
  `---\nname: ia-authoring\ndescription: Author or review IA records in this workspace.\n---\n\n${PACKET_MARKER}\n\nSource revision: ${revision}\n\nFind a word and its schema with \`ia vocabulary <word> --schema\`. Check records with \`ia validate\`. Inspect an admitted record with \`ia inspect <identity>\`. Validation establishes conformance to the declared schemas, not design quality.\n`;
/**
 * A hand-built packet whose every section renders: an unresolved system line beside a resolved one with no steward, a
 * mandate with each optional field and one with none, a multi-line non-ASCII `says`, a backtick in a path and a pipe
 * in a catalog row. Real packets carry five intent rows and four phase rows; the adapter renders whatever rows it gets.
 */
const HAND: PositionPacket = {
  format: 'ia.position-packet.v1',
  revision: 'a'.repeat(64),
  body: 'b'.repeat(64),
  seat: {
    identity: 'workspace-system/definition/workspace/acme',
    sources: ['.ia/src @authored', 'vendor/kit @adopted'],
    systems: 2,
    steward: '@agent acme',
  },
  participants: [{ identity: participant, says: 'Operates in acme —\n  any vendor, café.' }],
  mandates: [
    {
      identity: 'agent-system/policy/mandate/acme-mandate',
      participant,
      moves: ['Observation', 'Verification'],
      scope: ['workspace-system/definition/workspace/acme'],
      excludedWords: ['schema'],
      covers: ['src/`odd`/'],
    },
    { identity: 'agent-system/policy/mandate/open-mandate', participant, scope: [] },
  ],
  systems: [
    { identity: '@system missing-system', words: 'unresolved', steward: 'unresolved' },
    {
      identity: 'floor/definition/system/work-system',
      words: ['plan', 'task'],
      band: 90,
      reach: 'ia position --seat floor/definition/system/work-system',
    },
  ],
  tallies: [
    { word: 'agent', count: 1 },
    { word: 'mandate', count: 2 },
  ],
  intents: [
    {
      shape: 'governance',
      category: 'rule',
      primitive: 'Inference',
      phase: 'plan',
      kinds: ['governance', 'policy'],
      lanes: ['authority'],
      predicates: ['govern'],
      priming: [],
      words: ['law'],
    },
  ],
  phases: [{ phase: 'orient', primitives: ['Memory', 'Attention'], changes: '--phase selects the cell' }],
  commands: [
    {
      command: 'ia next',
      mode: 'read',
      move: 'Observation',
      refuses: 'several plans | none',
      next: 'ia next --seat <plan>',
    },
  ],
  lines: ['run ia position; if it refuses, run the command it names'],
  provenance: { revision: 'a'.repeat(64), slug: 'acme' },
};
const NOTE: PacketHostNote = {
  revision: 'a'.repeat(64),
  capturedRevision: 'c'.repeat(64),
  freshness: 'stale',
  key: { shape: 'context', phase: 'orient', depth: 0, budget: 0 },
  installed: 'unknown (no join checked here)',
};
const sha256 = (text: string): string => createHash('sha256').update(Buffer.from(text, 'utf8')).digest('hex');
const packetOf = (root: string): PacketOutput => {
  const db = database(root);
  return renderPacket(db, db.resolveScope().token, CATALOG);
};
const render = (output: PacketOutput, host: PacketHost, target: PacketTarget): HostOutput =>
  renderHost(host, output.packet, output.digest, output.hostNote, target);
/** R19's fresh-init fixture packet and this repository's own, each rendered once per test. */
const corpora = (): readonly (readonly [string, PacketOutput])[] => [
  ['fresh init', packetOf(freshInit())],
  ['repository', packetOf(repository)],
];
const entryOf = (output: PacketOutput, host: PacketHost, target: PacketTarget): string =>
  render(output, host, target).files[0]!.text;
/** The packet's sections of an entry file: from its title to the line before the provenance line. */
const block = (text: string): string =>
  text.slice(text.indexOf('# IA position packet'), text.indexOf('\nia-generated '));
/** The entries an entry file renders: the list items and table body rows above the provenance line, and that line. */
function entries(text: string): number {
  const lines = text.split('\n'),
    provenance = lines.findIndex((line) => line.startsWith('ia-generated '));
  let count = 1,
    rows = 0;
  for (const line of lines.slice(0, provenance)) {
    if (line.startsWith('- ')) count++;
    if (!line.startsWith('|')) rows = 0;
    else if (++rows > 2) count++;
  }
  return count;
}
const headings = (text: string): readonly string[] =>
  text
    .split('\n')
    .filter((line) => line.startsWith('## '))
    .map((line) => line.slice(3));
/** The list items under `heading`. */
const items = (text: string, heading: string): readonly string[] => {
  const lines = text.split('\n'),
    start = lines.indexOf(`## ${heading}`),
    end = lines.findIndex((line, index) => index > start && line.startsWith('#'));
  return lines.slice(start + 1, end === -1 ? undefined : end).filter((line) => line.startsWith('- '));
};

it('renders each host and target its entry file and ia-authoring skills, never an agent file, each with the marker', () => {
  for (const [corpus, output] of corpora()) {
    expect(output.packet.provenance.slug, corpus).toBe(corpus === 'fresh init' ? 'demo' : 'language-workspace');
    for (const host of HOSTS)
      for (const target of TARGETS) {
        const { files, receipt } = render(output, host, target),
          name = `${corpus} ${host} ${target}`;
        expect(
          files.map((file) => file.path),
          name,
        ).toEqual(PATHS[host][target]);
        expect(
          receipt.files.map((file) => file.path),
          name,
        ).toEqual(PATHS[host][target]);
        expect(
          files.some((file) => file.path.startsWith('.claude/agents')),
          name,
        ).toBe(false);
        expect(
          files[0]!.text.startsWith(`${PACKET_MARKER}\n\n# IA position packet: ${output.packet.provenance.slug}\n`),
          name,
        ).toBe(true);
        // Each skill keeps its YAML frontmatter first, then a blank line and the marker.
        for (const file of files.slice(1)) {
          const lines = file.text.split('\n');
          expect(lines.slice(0, 6), `${name} ${file.path}`).toEqual([
            '---',
            'name: ia-authoring',
            lines[2],
            '---',
            '',
            PACKET_MARKER,
          ]);
          expect(lines[2]!.startsWith('description: '), `${name} ${file.path}`).toBe(true);
        }
      }
  }
});

it("keeps each ia-authoring skill's text byte for byte, its marker line the new marker", () => {
  // The repository's skills are the files this repository commits, which `pnpm projections:generate` renders with
  // this adapter since milestone position-packet task replace-renderers: the 1.x marker is gone from both.
  const own = packetOf(repository);
  for (const host of HOSTS)
    for (const file of render(own, host, 'repository').files.slice(1)) {
      const committed = readFileSync(resolve(repository, file.path), 'utf8');
      expect(file.text, `${host} ${file.path}`).toBe(committed);
      expect(committed.split('\n'), `${host} ${file.path}`).not.toContain(LEGACY);
    }
  // A consumer's skill names the packet's revision, as the consumer renderer named the admitted one.
  const fresh = packetOf(freshInit());
  for (const host of HOSTS)
    expect(render(fresh, host, 'consumer').files[1]!.text, host).toBe(consumerSkill(fresh.packet.revision));
});

it("renders entryCount(packet) entries in the packet's field order, on a fresh init and on this repository, one participant here", () => {
  const outputs = corpora();
  for (const [name, output] of outputs) {
    for (const host of HOSTS)
      for (const target of TARGETS) {
        const text = entryOf(output, host, target);
        expect(entries(text), `${name} ${host} ${target}`).toBe(entryCount(output.packet));
        expect(render(output, host, target).receipt.entries, `${name} ${host} ${target}`).toBe(
          entryCount(output.packet),
        );
        expect(headings(text), `${name} ${host} ${target}`).toEqual([
          'Seat',
          'Participants',
          'Mandates',
          'Systems',
          'Captured records',
          'Intent shapes',
          'Phases',
          'Commands',
          'SPEC lines',
          ...(target === 'consumer' ? ['Host note (not part of the packet)'] : []),
        ]);
      }
    expect(items(entryOf(output, 'claude', 'repository'), 'Systems').length, name).toBe(output.packet.systems.length);
  }
  // This repository's packet names its one participant (plan task self-host-participant-records).
  const own = entryOf(outputs[1]![1], 'claude', 'repository');
  expect(items(own, 'Participants')).toEqual([
    '- `agent-system/binding/agent/language-participant`: The IDE agent operating in the language workspace, any vendor.',
  ]);
  expect(items(own, 'Mandates')).toEqual([
    '- `agent-system/policy/mandate/language-mandate`: participant `agent-system/binding/agent/language-participant`; moves Observation, Verification, Synthesis; scope `workspace-system/definition/workspace/language-workspace`; covers `.ia/src/`',
  ]);
});

it('renders byte-equal packet sections for claude and codex, and for both targets: only the path differs', () => {
  for (const [, output] of corpora()) {
    const sections = block(entryOf(output, 'claude', 'repository'));
    expect(sections.startsWith('# IA position packet: ')).toBe(true);
    expect(sections).toContain('## SPEC lines');
    for (const host of HOSTS) for (const target of TARGETS) expect(block(entryOf(output, host, target))).toBe(sections);
    // In one target the two hosts' entry files differ only in the adapter the provenance line names.
    for (const target of TARGETS)
      expect(entryOf(output, 'codex', target)).toBe(
        entryOf(output, 'claude', target).replace(/ ia-claude(@\S+)?\n/, (_, at) => ` ia-codex${at ?? ''}\n`),
      );
  }
});

it('names the adapter version and renders the host note in the consumer target only', () => {
  const output = packetOf(freshInit()),
    { packet, digest: packetDigest } = output;
  for (const host of HOSTS) {
    const repositoryText = entryOf(output, host, 'repository'),
      consumerText = entryOf(output, host, 'consumer');
    expect(repositoryText.endsWith(`\n\nia-generated ${packet.revision} ${packetDigest} ia-${host}\n`), host).toBe(
      true,
    );
    for (const file of render(output, host, 'repository').files) {
      expect(file.text, `${host} ${file.path}`).not.toContain('Host note');
      expect(file.text, `${host} ${file.path}`).not.toContain(`@${version}`);
    }
    expect(consumerText.split('\n').slice(-8, -1), host).toEqual([
      `ia-generated ${packet.revision} ${packetDigest} ia-${host}@${version}`,
      '',
      '## Host note (not part of the packet)',
      '',
      '- freshness no-capture',
      '- installed unknown (no join checked here)',
      "- key seat the repository's workspace, shape context, phase orient, depth 0, budget 0",
    ]);
    expect(consumerText.endsWith('budget 0\n'), host).toBe(true);
    // The receipt names the adapter with its version in either target.
    for (const target of TARGETS)
      expect(render(output, host, target).receipt.adapter, `${host} ${target}`).toBe(`ia-${host}@${version}`);
  }
});

it('renders a hand-built packet to exactly this text, every section and its markup', () => {
  const { files } = renderHost('claude', HAND, digest(HAND), NOTE, 'consumer');
  expect(files[0]!.text).toBe(
    [
      PACKET_MARKER,
      '',
      '# IA position packet: acme',
      '',
      '## Seat',
      '',
      '- workspace `workspace-system/definition/workspace/acme`; sources `.ia/src @authored`, `vendor/kit @adopted`; systems 2; steward `@agent acme`',
      '',
      '## Participants',
      '',
      '- `agent-system/binding/agent/acme`: Operates in acme — any vendor, café.',
      '',
      '## Mandates',
      '',
      '- `agent-system/policy/mandate/acme-mandate`: participant `agent-system/binding/agent/acme`; moves Observation, Verification; scope `workspace-system/definition/workspace/acme`; excluded words schema; covers ``src/`odd`/``',
      '- `agent-system/policy/mandate/open-mandate`: participant `agent-system/binding/agent/acme`; scope none',
      '',
      '## Systems',
      '',
      '- `@system missing-system`: words unresolved; steward unresolved',
      '- `floor/definition/system/work-system`: words plan, task; band 90; reach `ia position --seat floor/definition/system/work-system`',
      '',
      '## Captured records',
      '',
      '- agent 1',
      '- mandate 2',
      '',
      '## Intent shapes',
      '',
      '| shape | category | primitive | phase | kinds | lanes | predicates | priming | words |',
      '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
      '| governance | rule | Inference | plan | governance, policy | authority | govern | none | law |',
      '',
      '## Phases',
      '',
      '| phase | primitives | what --phase changes |',
      '| --- | --- | --- |',
      '| orient | Memory, Attention | --phase selects the cell |',
      '',
      '## Commands',
      '',
      '| command | mode | move | refuses | next |',
      '| --- | --- | --- | --- | --- |',
      '| `ia next` | read | Observation | several plans \\| none | `ia next --seat <plan>` |',
      '',
      '## SPEC lines',
      '',
      '- run ia position; if it refuses, run the command it names',
      '',
      `ia-generated ${'a'.repeat(64)} ${digest(HAND)} ia-claude@${version}`,
      '',
      '## Host note (not part of the packet)',
      '',
      '- freshness stale',
      '- installed unknown (no join checked here)',
      "- key seat the repository's workspace, shape context, phase orient, depth 0, budget 0",
      '',
    ].join('\n'),
  );
  expect(entries(files[0]!.text)).toBe(entryCount(HAND));
  expect(entryCount(HAND)).toBe(13);
  // With no participant and no seat identity, the seat line says so and a section with no entry has no heading.
  const empty: PositionPacket = {
    ...HAND,
    seat: { sources: [], systems: 0, participants: 'none (no authored @mandate names an @agent)' },
    participants: [],
    mandates: [],
    systems: [],
    tallies: [],
    commands: [],
    provenance: { revision: HAND.revision },
  };
  const text = renderHost('codex', empty, digest(empty), NOTE, 'repository').files[0]!.text;
  expect(block(text)).toBe(
    [
      '# IA position packet',
      '',
      '## Seat',
      '',
      '- workspace undeclared; sources none; systems 0; participants none (no authored `@mandate` names an `@agent`)',
      '',
      '## Intent shapes',
      '',
      '| shape | category | primitive | phase | kinds | lanes | predicates | priming | words |',
      '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
      '| governance | rule | Inference | plan | governance, policy | authority | govern | none | law |',
      '',
      '## Phases',
      '',
      '| phase | primitives | what --phase changes |',
      '| --- | --- | --- |',
      '| orient | Memory, Attention | --phase selects the cell |',
      '',
      '## SPEC lines',
      '',
      '- run ia position; if it refuses, run the command it names',
      '',
    ].join('\n'),
  );
  expect(entries(text)).toBe(entryCount(empty));
});

it('renders each bare IA word token in free text as a code span, the packet and its entries unchanged', () => {
  const worded: PositionPacket = {
    ...HAND,
    participants: [
      { identity: participant, says: 'Answers for @workspace and @plan owners; mail a@b.c; see @inventarch/db.' },
    ],
    commands: [{ ...HAND.commands[0]!, refuses: 'no @workspace; several @plan records' }],
    lines: [
      'author an @observation; quote `@spec` as authored',
      'run `ia author @plan` first; see `scope [@workspace demo]`, ``x @plan @mandate y`` and @agent',
      'a ` no run closes, then @plan',
    ],
  };
  const before = JSON.stringify(worded),
    /** A bare token outside every code span, as the adapter finds one: what GitHub would render as a mention. */
    bare = (text: string): readonly string[] =>
      text.replace(/(`+)[\s\S]*?(?<!`)\1(?!`)/g, '').match(/(?<![\w.\-/@`])@[a-z][a-z0-9-]*(?![\w\-/@])/g) ?? [];
  for (const host of HOSTS)
    for (const target of TARGETS) {
      const { files, receipt } = renderHost(host, worded, digest(worded), NOTE, target),
        text = files[0]!.text,
        name = `${host} ${target}`;
      expect(items(text, 'Participants'), name).toEqual([
        '- `agent-system/binding/agent/acme`: Answers for `@workspace` and `@plan` owners; mail a@b.c; see @inventarch/db.',
      ]);
      expect(text, name).toContain('| `ia next` | read | Observation | no `@workspace`; several `@plan` records |');
      // A token already in an authored code span stays as authored, wherever in the span it stands, and so does the
      // span: wrapping a token after its first character would close the span early and leave the token bare.
      expect(items(text, 'SPEC lines'), name).toEqual([
        '- author an `@observation`; quote `@spec` as authored',
        '- run `ia author @plan` first; see `scope [@workspace demo]`, ``x @plan @mandate y`` and `@agent`',
        // A backtick no run closes is literal text, so the token's fence is longer than it, and never closes it.
        '- a ` no run closes, then ``@plan``',
      ]);
      expect(bare(text), name).toEqual([]);
      expect(entries(text), name).toBe(entryCount(worded));
      expect(receipt.packetDigest, name).toBe(digest(worded));
    }
  expect(JSON.stringify(worded)).toBe(before);
  // A token touching a backtick outside a span is left as authored: no fence could wrap it without joining that run.
  const touching: PositionPacket = { ...HAND, lines: ['a stray `@plan'] };
  expect(
    items(renderHost('claude', touching, digest(touching), NOTE, 'repository').files[0]!.text, 'SPEC lines'),
  ).toEqual(['- a stray `@plan']);
  // The seat line's own text when no participant renders, and the receipt's null slug for a packet without one.
  const empty: PositionPacket = {
    ...HAND,
    seat: { sources: [], systems: 0, participants: 'none (no authored @mandate names an @agent)' },
    participants: [],
    mandates: [],
    provenance: { revision: HAND.revision },
  };
  const rendered = renderHost('claude', empty, digest(empty), NOTE, 'repository');
  expect(bare(rendered.files[0]!.text)).toEqual([]);
  expect(empty.seat.participants).toBe('none (no authored @mandate names an @agent)');
  expect(rendered.receipt.slug).toBeNull();
  // This repository's packet, the committed CLAUDE.md, names `@workspace` and `@plan` only in code spans.
  for (const host of HOSTS) expect(bare(entryOf(packetOf(repository), host, 'repository')), host).toEqual([]);
});

it("prints the host note's key as ia position prints it, and pads a code span a backtick touches", () => {
  const key = (seat: NonNullable<PacketHostNote['key']['seat']>, word?: string): string =>
    renderHost(
      'claude',
      HAND,
      digest(HAND),
      { ...NOTE, key: { ...NOTE.key, seat, ...(word === undefined ? {} : { word }) } },
      'consumer',
    )
      .files[0]!.text.trimEnd()
      .split('\n')
      .at(-1)!;
  expect(key(participant, 'law')).toBe(
    `- key seat ${participant}, shape context, phase orient, depth 0, budget 0, word law`,
  );
  // A location seat as the caller spelled it, the repository root `''` as `.`, as apps/cli's keyText prints it.
  expect(key({ path: 'packages/runtime' })).toBe(
    '- key seat packages/runtime, shape context, phase orient, depth 0, budget 0',
  );
  expect(key({ path: '' })).toBe('- key seat ., shape context, phase orient, depth 0, budget 0');
  // A value a backtick starts or ends is padded inside its fence, one backtick longer than the longest run it holds.
  const edged: PositionPacket = { ...HAND, mandates: [{ ...HAND.mandates[1]!, covers: ['`edge`', 'a``b'] }] };
  expect(items(renderHost('codex', edged, digest(edged), NOTE, 'repository').files[0]!.text, 'Mandates')).toEqual([
    `- \`agent-system/policy/mandate/open-mandate\`: participant \`${participant}\`; scope none; covers \`\` \`edge\` \`\`, \`\`\`a\`\`b\`\`\``,
  ]);
});

it("returns a receipt whose file digests are the SHA-256 of each file's UTF-8 text, the applying fields left open", () => {
  const { files, receipt } = renderHost('claude', HAND, digest(HAND), NOTE, 'repository');
  // The participant's `says` is not ASCII, so its UTF-8 bytes are what the digest covers.
  expect(Buffer.byteLength(files[0]!.text, 'utf8')).toBeGreaterThan(files[0]!.text.length);
  expect(receipt).toEqual({
    format: 'ia.packet-receipt.v1',
    host: 'claude',
    cli: null,
    adapter: `ia-claude@${version}`,
    revision: HAND.revision,
    slug: 'acme',
    packetDigest: digest(HAND),
    bodyDigest: HAND.body,
    entries: 13,
    files: files.map((file) => ({ path: file.path, sha256: sha256(file.text) })),
    removed: [],
    foreign: [],
    guard: 'none',
    hostNote: NOTE,
    participants: [participant],
    mandates: ['agent-system/policy/mandate/acme-mandate', 'agent-system/policy/mandate/open-mandate'],
    writtenAt: null,
  });
  for (const [corpus, output] of corpora())
    for (const host of HOSTS)
      for (const target of TARGETS) {
        const rendered = render(output, host, target);
        expect(rendered.receipt.files, `${corpus} ${host} ${target}`).toEqual(
          rendered.files.map((file) => ({ path: file.path, sha256: sha256(file.text) })),
        );
      }
});

it('gives frozen output, byte-equal at two absolute roots, naming neither root', () => {
  const roots = [freshInit(), freshInit()],
    [first, second] = roots.map((root) => {
      const output = packetOf(root);
      return HOSTS.flatMap((host) => TARGETS.map((target) => render(output, host, target)));
    });
  expect(JSON.stringify(second)).toBe(JSON.stringify(first));
  for (const [index, root] of roots.entries())
    for (const { files } of [first, second][index]!)
      for (const file of files)
        for (const spelling of [root, root.replaceAll('\\', '/'), root.replaceAll('\\', '\\\\')])
          expect(file.text).not.toContain(spelling);
  const result = first![0]!;
  expect(
    [result, result.files, result.files[0], result.receipt, result.receipt.files, result.receipt.hostNote].map(
      Object.isFrozen,
    ),
  ).toEqual([true, true, true, true, true, true]);
  // The caller's host note is copied, not frozen in place.
  const note = { ...NOTE, key: { ...NOTE.key } };
  expect(renderHost('codex', HAND, digest(HAND), note, 'consumer').receipt.hostNote).toEqual(note);
  expect([Object.isFrozen(note), Object.isFrozen(note.key)]).toEqual([false, false]);
});

it("refuses an unknown host or target, and a digest that is not the packet's", () => {
  const invalid = expect.objectContaining({ code: 'IA-RUNTIME-REQUEST-INVALID' });
  for (const host of ['cursor', 'toString'])
    expect(() => renderHost(host as PacketHost, HAND, digest(HAND), NOTE, 'consumer')).toThrow(invalid);
  expect(() => renderHost('claude', HAND, digest(HAND), NOTE, 'ci' as PacketTarget)).toThrow(invalid);
  expect(() => renderHost('claude', HAND, 'f'.repeat(64), NOTE, 'consumer')).toThrow(invalid);
});
