/**
 * `ia vocabulary`: docs/specs/consumer-cli-contract/README.md §2.2.
 *
 * Reads the catalogue shipped inside the installed package at `assets/vocabulary.json` and nothing else, so the
 * command works in an empty directory with no `.ia` tree anywhere. The asset is generated by
 * `tools/native/public-vocabulary.ts` under the `vocabulary:check` drift gate. It carries no example field
 * today, so `--example` reports that plainly and never composes one.
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fieldTypeText } from '@inventarch/compliance';
import type { Context, Result } from './consumer.js';
import { Refusal, respell } from './consumer.js';
import { nearestTokens } from './commands.js';
import type { Capabilities, Field, Token } from './render.js';
import { atom, document, entry, fieldRows, headerLine, sectionLabel, truncateDigest, words } from './render.js';

interface SchemaSection {
  readonly name: string;
  readonly required: boolean;
}
interface SchemaField {
  readonly path: string;
  readonly type: unknown;
  readonly required: boolean;
  readonly description?: string;
  /** W0 narrowings the catalogue carries beside the type: `id in [...]`, `ref to <word>`, `text form <form>`. */
  readonly values?: readonly string[];
  readonly target?: string;
  readonly form?: string;
}
interface SchemaEdge {
  readonly predicate: string;
  /** The rule's direction relative to the word's records: `out` for the active and present spellings, `in` for the inverse. */
  readonly direction: 'out' | 'in';
  /** The verb as the schema spells it; the row's label. */
  readonly spelling: string;
  readonly target: string;
  readonly cardinality: string;
  readonly required: boolean;
}
interface WordSchema {
  readonly name: string;
  readonly path: string;
  readonly closed: boolean;
  readonly sections: readonly SchemaSection[];
  readonly fields: readonly SchemaField[];
  readonly edges: readonly SchemaEdge[];
}
export interface Word {
  readonly word: string;
  readonly owner: string;
  readonly kind: string;
  readonly category: string;
  readonly facets: readonly string[];
  readonly identity: string;
  readonly description: string;
  readonly schema: WordSchema;
  readonly kernelMembers: readonly string[];
  readonly consumer: string;
  /** Absent from every word the generator emits today; §2.2 and §8 both record that. */
  readonly example?: string;
}
export interface Catalogue {
  readonly version: number;
  readonly language: string;
  readonly status: string;
  readonly sourceDigest: string;
  readonly words: readonly Word[];
}

export const CATALOGUE_PATH = 'assets/vocabulary.json';
export function readCatalogue(packageRoot: string): Catalogue {
  const path = resolve(packageRoot, CATALOGUE_PATH);
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as Catalogue;
  } catch (error) {
    throw new Refusal(
      'IA-CLI-FAILED',
      `The shipped vocabulary catalogue at ${path} could not be read: ${error instanceof Error ? error.message : String(error)}`,
      3,
      { path },
      'Run "ia doctor" for this installation\'s install channel and reinstall @inventarch/cli through it; the catalogue ships with the package and is not read from the workspace.',
    );
  }
}

/** The catalogue's type as a string (it is JSON), spelled with its W0 narrowing by the language's one renderer. */
const typeText = (field: SchemaField): string =>
  fieldTypeText({ ...field, type: typeof field.type === 'string' ? field.type : JSON.stringify(field.type) });
const reduceSchema = (schema: WordSchema, full: boolean): unknown =>
  full ? schema : { name: schema.name, path: schema.path, closed: schema.closed };
const projectWord = (word: Word, full: boolean, example: boolean): unknown => ({
  ...word,
  schema: reduceSchema(word.schema, full),
  ...(example && word.example !== undefined ? { example: word.example } : {}),
});

const detail = (word: Word, full: boolean, caps: Capabilities): readonly (readonly string[])[] => {
  const pair = (label: string, value: readonly Token[]): Field => ({ label, value });
  const blocks: (readonly string[])[] = [
    headerLine('Word', `@${word.word}`, [{ text: word.owner, column: 50 }], caps),
    entry([words(word.description)], { depth: 1 }, caps),
    [
      sectionLabel('Definition', caps),
      ...fieldRows(
        [
          pair('Kind', words(word.kind)),
          pair('Category', words(word.category)),
          pair('Facets', [
            atom(word.facets.join(', '), null, 0),
            ...(word.facets.length > 1 ? words('(the first is the default)', 'dim', 2) : []),
          ]),
          pair('Identity', [atom(word.identity, 'cyan', 0)]),
          pair('Consumer', words(word.consumer)),
        ],
        { depth: 1 },
        caps,
      ),
    ],
    [
      sectionLabel('Schema', caps),
      ...fieldRows(
        [
          pair('Name', [atom(word.schema.name, 'cyan', 0)]),
          pair('Source', [atom(word.schema.path, 'cyan', 0)]),
          pair('Sections', words(word.schema.closed ? 'closed ordinary sections' : 'open ordinary sections')),
          pair(
            'Required',
            words(
              word.schema.sections
                .filter((row) => row.required)
                .map((row) => row.name)
                .join(', ') || 'none',
            ),
          ),
          pair(
            'Optional',
            words(
              word.schema.sections
                .filter((row) => !row.required)
                .map((row) => row.name)
                .join(', ') || 'none',
            ),
          ),
        ],
        { depth: 1 },
        caps,
      ),
    ],
  ];
  if (word.kernelMembers.length > 0)
    blocks.push([
      sectionLabel('Closed kernel members', caps),
      ...entry([words(word.kernelMembers.join(', '))], { depth: 1 }, caps),
    ]);
  if (!full) {
    blocks.push(
      entry(
        [words(`Run "ia vocabulary ${word.word} --schema" for fields and relationships.`, 'dim')],
        { depth: 0 },
        caps,
      ),
    );
    return blocks;
  }
  blocks.push([
    sectionLabel('Fields', caps),
    ...(word.schema.fields.length === 0
      ? entry([words('None; the shared schema grammar applies.')], { depth: 1 }, caps)
      : fieldRows(
          word.schema.fields.map((field) => ({
            label: field.path,
            value: [atom(typeText(field), null, 0), ...words(field.required ? 'required' : 'optional', 'dim', 2)],
            // A field's quoted schema description, when it has one, sits under its row at the value column.
            note: field.description ? words(field.description, 'dim') : undefined,
          })),
          { depth: 1 },
          caps,
        )),
  ]);
  if (word.schema.edges.length > 0)
    blocks.push([
      sectionLabel('Relationships', caps),
      ...fieldRows(
        word.schema.edges.map((edge) => ({
          label: edge.spelling,
          value: [
            atom(edge.target, 'cyan', 0),
            ...words(
              `${edge.cardinality}; ${edge.required ? 'required' : 'optional'}${edge.direction === 'in' ? '; inbound' : ''}`,
              'dim',
              2,
            ),
          ],
        })),
        { depth: 1 },
        caps,
      ),
    ]);
  return blocks;
};

const filterText = (context: Context): string => {
  const parts: string[] = [];
  const word = context.args.positionals[0];
  if (word !== undefined) parts.push(`@${word.replace(/^@/, '')}`);
  for (const domain of context.args.list('domain')) parts.push(`--domain ${domain}`);
  for (const kind of context.args.list('kind')) parts.push(`--kind ${kind}`);
  const search = context.args.value('search');
  if (search !== undefined) parts.push(`--search ${search}`);
  return parts.length === 0 ? 'no filters' : parts.join(' ');
};

export function runVocabulary(context: Context): Result {
  const { args, caps, json } = context;
  const catalogue = readCatalogue(context.host.packageRoot);
  const requested = args.positionals[0]?.replace(/^@/, '');
  const full = args.flag('schema'),
    wantsExample = args.flag('example');

  if (requested !== undefined && !catalogue.words.some((word) => word.word === requested)) {
    const [nearest, ...also] = nearestTokens(
      requested,
      catalogue.words.map((word) => word.word),
    );
    // Design row 27: one command, the nearest word with the rest of the invocation as understood; any other near word
    // is named, not offered as a command.
    const others = also.length === 0 ? '' : ` Also near: ${also.map((name) => `@${name}`).join(', ')}.`;
    throw new Refusal(
      'IA-CLI-USAGE',
      `Unknown word @${requested}; the shipped catalogue carries ${catalogue.words.length} words`,
      2,
      null,
      nearest === undefined
        ? 'Run "ia vocabulary" to list every word.'
        : `Did you mean "${respell(context, { positionals: [nearest] })}"?${others}`,
    );
  }

  const domains = args.list('domain'),
    kinds = args.list('kind');
  const search = args.value('search')?.toLowerCase();
  const selected = catalogue.words.filter(
    (word) =>
      (requested === undefined || word.word === requested) &&
      (domains.length === 0 || domains.includes(word.owner)) &&
      (kinds.length === 0 || kinds.includes(word.kind)) &&
      (search === undefined ||
        word.word.toLowerCase().includes(search) ||
        word.description.toLowerCase().includes(search)),
  );

  const single = selected.length === 1 && requested !== undefined ? selected[0]! : undefined;
  const exampleMissing = wantsExample && single !== undefined && single.example === undefined;
  const exitCode = selected.length === 0 || exampleMissing ? 1 : 0;

  if (json) {
    const body = {
      version: catalogue.version,
      language: catalogue.language,
      status: catalogue.status,
      sourceDigest: catalogue.sourceDigest,
      words: selected.map((word) => projectWord(word, full, wantsExample)),
    };
    return { exitCode, stdout: JSON.stringify(body) + '\n', stderr: '' };
  }

  if (selected.length === 0)
    return {
      exitCode,
      stdout: '',
      stderr: document([
        entry(
          [
            words(`No word matches ${filterText(context)}.`),
            words(`The shipped catalogue carries ${catalogue.words.length} words.`, 'dim'),
          ],
          { depth: 0, symbol: 'info' },
          caps,
        ),
      ]),
    };

  if (single !== undefined) {
    const blocks = [...detail(single, full, caps)];
    if (wantsExample && single.example !== undefined)
      blocks.push([sectionLabel('Example', caps), ...entry([[atom(single.example, null, 0)]], { depth: 1 }, caps)]);
    return {
      exitCode,
      stdout: document(blocks, { leadingBlank: true }),
      stderr: exampleMissing ? `No example is shipped for @${single.word}.\n` : '',
    };
  }

  return {
    exitCode,
    stdout: document(
      [
        headerLine(
          'Vocabulary',
          `${selected.length} of ${catalogue.words.length} words`,
          [{ text: `source digest ${truncateDigest(catalogue.sourceDigest, caps.ascii)}`, column: 50 }],
          caps,
        ),
        [
          sectionLabel('Words', caps),
          ...fieldRows(
            selected.map((word) => ({ label: `@${word.word}`, value: words(word.description) })),
            { depth: 1 },
            caps,
          ),
        ],
        entry(
          [words('Run "ia vocabulary <word> --schema" for one word\'s fields and relationships.', 'dim')],
          { depth: 0 },
          caps,
        ),
      ],
      { leadingBlank: true },
    ),
    stderr: '',
  };
}
